### ISSUE TITLE
本地配置文件改名后报错

### ISSUE THREAD

**Issue by jdjxk** [chen08209/FlClash#10]
复现步骤：
添加配置文件，编辑修改名称
配置自动转变为URL形式，出现更新按钮，点击更新后，报错如下：
DioException [unknown]: null Error: Invalid argument(s): No host specified in URI

**Comment by chen08209** [comment]
最新版应该已经修复了

**Comment by jdjxk** [comment]
0.8.12版本，改名后更新按钮仍然出现

**Comment by Mlearn** [comment]
Android 0.8.53 版本，相同报错
