### ISSUE TITLE
辛苦大佬支持下mihomo内核的unified-delay与tcp-concurrent特性

### ISSUE THREAD

**Issue by Kia678** [chen08209/FlClash#101]
如题：辛苦大佬支持下mihomo内核的unified-delay与tcp-concurrent、global-client-fingerprint特性
![image](https://github.com/chen08209/FlClash/assets/85081567/a1fb368e-01c3-4704-aa60-f85b27641c29)

并考虑内置geoip.dat与geosite.dat文件和自动更新功能
![image](https://github.com/chen08209/FlClash/assets/85081567/dd74e322-55eb-4099-9dda-20f9fbd6b1f4)

**Comment by chen08209** [comment]
已经内置geoip和geosite，自动更新不考虑，global-client-fingerprint目前不知道有什么用途
