### ISSUE TITLE
切换配置文件后，节点也变化了，但是打开油管，显示的归属地仍然是之前配置文件的地区。试过浏览器无痕模式也是同样情况。

### ISSUE THREAD

**Issue by daveleeyee2022** [chen08209/FlClash#103]
切换配置文件后，节点也变化了，但是打开油管，显示的归属地仍然是之前配置文件的地区。试过浏览器无痕模式也是同样情况。

**Comment by chen08209** [comment]
是否是因为缓存还是什么，浏览器检测ip通常需要把浏览器关闭一下，首页的检测ip也能提供一定程度的参考

**Comment by chen08209** [comment]
是否是因为缓存还是什么，浏览器检测ip通常需要把浏览器关闭一下，首页的检测ip也能提供一定程度的参考
