### ISSUE TITLE
android  访问控制 修改后需要二次确认

### ISSUE THREAD

**Issue by iKun10001** [chen08209/FlClash#104]
大佬 没有二次确认 有时候误触了 就要重新全部点一遍呢  真的非常需要`
要是能把他放到二级菜单里就更好了 
谢谢大佬 真的是非常棒的项目

**Comment by chen08209** [comment]
是全选和反选的二次确认吗？访问控制这块之后应该会有比较大的变化，因为原先这个就是因为有部分页面不知道怎么处理而导致很多地方不完善，现在有了解决方案，应该会在晚一些时候处理

**Comment by iKun10001** [comment]
> 是全选和反选的二次确认吗？访问控制这块之后应该会有比较大的变化，因为原先这个就是因为有部分页面不知道怎么处理而导致很多地方不完善，现在有了解决方案，应该会在晚一些时候处理

实在退出时 加一个确认弹窗   我手机放口袋里有时候会误触````````结果一退出他就直接保存了`呜呜呜`有几天谷歌连不上网 再检查一次才发现是这个问题
或者把这个选项放到二级菜单里  谢谢大佬
