### ISSUE TITLE
UA出现双版本号，会与Xboard识别客户端版本判断冲突

### ISSUE THREAD

**Issue by ckaak** [chen08209/FlClash#106]
现在的UA是：FlClash/v0.8.35 clash-verge/v1.6.6 Platform/android

但是如果机场使用Xboard面板，https://github.com/cedar2025/Xboard/blob/dev/app/Http/Controllers/V1/Client/ClientController.php  在订阅判断上，会识别clash-verge软件版本号，如果低于就不下发节点。FlClash有v1.6.6 v0.8.35双版本就会出现问题。

实际上可以像Hiddify一样，在后面加上ClashMeta v2ray sing-box内核识别。一样可以让面板正常下发节点。HiddifyNext/0.13.6 (windows) like ClashMeta v2ray sing-box

现在UA改成：FlClash/v0.8.35 /like ClashMeta Clash/android

原来FlClash UA是：clash.meta一样可以正常下发。

**Comment by chen08209** [comment]
目前支持切换ua，后续可能会考虑优化一下默认ua，比如去除clash.verge的版本号

**Comment by Kia678** [comment]
> 目前支持切换ua，后续可能会考虑优化一下默认ua，比如去除clash.verge的版本号

无法从订阅URL中获取到Hysteria2节点（鸡场配置中含Hysteria2）

**Comment by hulisang** [comment]
> > 目前支持切换ua，后续可能会考虑优化一下默认ua，比如去除clash.verge的版本号
> 
> 有个问题麻烦大佬看下：无法从订阅URL中获取到Hysteria2节点（鸡场配置中含Hysteria2）

订阅UA用clash-verge/v1.7.5就行了
