### ISSUE TITLE
当代理端口设置为7890时，socks5无法连接

### ISSUE THREAD

**Issue by UGYnpU2nuB8QCFqDrsWZgmxMBp43WQ** [chen08209/FlClash#116]
版本：0.8.38
平台：Windows，Android
当代理端口设置为7890时，socks5无法连接。

修改为其它端口后正常。

**Comment by long1215** [comment]
我也是一直默认7890  现在用不了

**Comment by chen08209** [comment]
原本默认覆盖了socks端口，http端口，如果配置文件中这些端口和mixed端口冲突，就会导致这种情况，现在已经回滚
