### ISSUE TITLE
从URL导入超时

### ISSUE THREAD

**Issue by apname** [chen08209/FlClash#119]
现在是十秒没获取到就显示超时，导致URL导入一直因为超时失败，希望延长到30秒或者1分钟

**Comment by gov360** [comment]
> 现在是十秒没获取到就显示超时，导致URL导入一直因为超时失败，希望延长到30秒或者1分钟

如果你处在慢速网络中，建议下载到本地，从而导入使用

**Comment by apname** [comment]
> > 现在是十秒没获取到就显示超时，导致URL导入一直因为超时失败，希望延长到30秒或者1分钟
> 
> 如果你处在慢速网络中，建议下载到本地，从而导入使用

你说有没有一种可能是订阅转换网站的处理时间过长？不少网站都得十几秒才能处理好
