### ISSUE TITLE
使用通知栏快捷方式开启后仪表盘开关状态未同步

### ISSUE THREAD

**Issue by AIsouler** [chen08209/FlClash#12]
https://github.com/chen08209/FlClash/assets/57941037/0f020360-bbea-4049-a167-84901662b66e

**Comment by chen08209** [comment]
偶发，还是必现

**Comment by AIsouler** [comment]
必现，具体场景为软件未在后台运行的情况下，使用快捷方式开启后再启动软件

**Comment by chen08209** [comment]
https://github.com/chen08209/FlClash/assets/66918471/981b50fe-0847-467d-adfa-af436c59f076

同品牌，通常情况下应该是没问题的，之后会尝试找下原因

**Comment by chen08209** [comment]
最新版本已解决
