### ISSUE TITLE
Custom User-Agent for each profile & autoUpdate time

### ISSUE THREAD

**Issue by APT-ZERO** [chen08209/FlClash#134]
Hello
Please add option to set different User-Agent for each profile
Including custom User-Agent

And when user clicks to add subscription url, let user to set auto-update time and user-agent, as if user use wrong user-agent then adding may fail
You can also set default auto-update time to 12Hours, 24h is too long (personal opinion)

Thank you

**Comment by chen08209** [comment]
应该不会考虑
