### ISSUE TITLE
希望手机端能支持在后台任务界面隐藏

### ISSUE THREAD

**Issue by AIsouler** [chen08209/FlClash#14]

**Comment by chen08209** [comment]
应该不会考虑，推荐通过磁贴进入。

**Comment by AIsouler** [comment]
好的，虽然可以通过磁贴开启代理服务而不进入软件，但是有时候需要切换节点，就必须进入软件了，个人感觉这类软件留在最近任务界面是多余的，一般开启后就很少再进入软件了，留在任务界面比较占位置，我是从surfboard转过来的，surfboard也有这个功能
