### ISSUE TITLE
相同的Clash规则，在Clash-verge-res可以使用，在Flclash无法使用，开启后的ip还是显示本地的ip，pc端和安卓端都一样

### ISSUE THREAD

**Issue by akiker233** [chen08209/FlClash#144]
相同的Clash自定义规则，在Clash-verge-res可以使用，在Flclash无法使用，开启后的ip还是显示本地的ip，pc端和安卓端都一样

**Comment by hujuying** [comment]
我也发现了，不过今天操作发现把ua修改为Clash-verge-res后解决了。默认的ua有的机场不识别。

**Comment by akiker233** [comment]
> 我也发现了，不过今天操作发现把ua修改为Clash-verge-res后解决了。默认的ua有的机场不识别。

ua不识别一般是无法获取订阅，但是我成功获取订阅了，就是连接之后ip还是显示本地的ip，Google也无法访问

**Comment by xingxin1590** [comment]
我安卓倒是可以把verge的配置导过来正常使用，没遇到过你那种问题，verge改的配置用的script脚本

**Comment by chen08209** [comment]
ip显示本地，两种可能，一是配置本身有问题，二是检测ip的网址被规则设置为直连

**Comment by akiker233** [comment]
> ip显示本地，两种可能，一是配置本身有问题，二是检测ip的网址被规则设置为直连

配置在Clash-verge-res可以正常使用，在ip.skk.moe那里检测ip全是国内，相当于没有开启
