### ISSUE TITLE
建议添加UWP应用回环解除工具

### ISSUE THREAD

**Issue by YanBai233** [chen08209/FlClash#148]
### 建议
- 建议内置一个 UWP 应用回环解除工具。

目前 FlClash 中，没有内置如《EnableLoopback Utility》一类的 UWP 应用回环解除工具，需要自行下载。
考虑到 Windows 中大部分自带组件无法直接使用系统代理，所以 UWP 应用回环解除工具在日常使用中十分重要。
所以，建议内置一个 UWP 应用回环解除工具，以降低使用成本

### 可以参考的 UWP 应用回环接触工具
| 链接 | 备注 |
| --- | --- |
| https://www.telerik.com/fiddler/add-ons | 已停止维护 |
| https://github.com/Kuingsmile/uwp-tool | 上一的重新签名版 |
| https://github.com/wherewhere/Windows-Loopback-Exemption-Manager?tab=readme-ov-file | 持续维护中；可靠性未知 |
| https://github.com/Richasy/LoopbackManager.Desktop | WinUI；软件过大 |

**Comment by MarkIvory2973** [comment]
赞同

**Comment by TwinTusks** [comment]
+1 期待能自带功能。
