### ISSUE TITLE
FlClash-0.8.45-windows-amd64-setup 安装之后，打开报错

### ISSUE THREAD

**Issue by 932808140** [chen08209/FlClash#151]
![image](https://github.com/user-attachments/assets/14750289-da54-4437-9e48-02cf979348f0)

**Comment by 932808140** [comment]
![image](https://github.com/user-attachments/assets/ee332c4c-c18d-4037-8fd8-5330a0105328)

**Comment by Tom20224** [comment]
我的也是这样，不知道为什么，不管是压缩文件还是安装包，都是这个样子

**Comment by twoone-3** [comment]
https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by chen08209** [comment]
无法复现，目前windows运行库相关问题，自行google解决

**Comment by ikun09** [comment]
解决方法安装微软Visual C++ Redistributable for Visual Studio 2015-2022 x64即可解决
[https://aka.ms/vs/17/release/vc_redist.x64.exe](https://aka.ms/vs/17/release/vc_redist.x64.exe)
