### ISSUE TITLE
[功能请求] 加入和clash verge rev一样的固定功能。

### ISSUE THREAD

**Issue by Hayakee** [chen08209/FlClash#153]
clash verge rev的图钉功能介绍 https://clash-verge-rev.github.io/faq/other.html#_6 。
整理了一下这玩意的应用场景体现一下这个功能的用处（和啥啥IP风险无关）。
假设我现在有两个机场，分别是奶昔和CTC一年不限时，平时主用奶昔。
首先将节点按地区分组，然后在地区里面也分两个组，以香港为例，分出大香港组，类型是url-test。然后在大香港组里面分出两个组，分别是奶昔和CTC的香港组，包含自家的香港节点，类型也是url-test。然后某些规则要走香港，用大香港组就行。各位的规则运用比我精通，就不多废话了。
设想如下场景，假如哪天奶昔被D，大香港组的url-test策略会自动换到CTC香港组，这是预期行为，但是CTC流量包是备用，主要花流量的是奶昔香港组，因此不可能一直使用CTC。
这样的场景下需求就出现了，奶昔恢复后，肯定是要自动切回奶昔香港组的。但是fallback没有这样的功能，实际上大香港组我也不想使用url-test，但是verge的图钉就是在url-test下使用。
回到verge的这种，我固定了奶昔香港组（图钉固定的是整个奶昔香港组，不是组里面的奶昔香港节点），只要奶昔香港组里的节点还有一个没超时就一直用，假如被D超时就自动切换到CTC，然后程序检测发现奶昔在线又自动换回去。
这种使用的场景个人感觉不算小众，无非就是多了一步把地区按照机场分组。
不知道开发者是否考虑？
这是示意图：
![image](https://github.com/user-attachments/assets/51987891-6627-459e-8c69-0ba48e315d4b)
![image](https://github.com/user-attachments/assets/721ffd2f-2ccc-4e04-b801-c2116e840d46)

**Comment by starifly** [comment]
+1，这个功能有必要

**Comment by zhiqiang02** [comment]
可以换个叫法

> Temporary Override Group Option
