### ISSUE TITLE
规则模式下不支持speedtest 测速

### ISSUE THREAD

**Issue by xjbc123** [chen08209/FlClash#154]
![Screenshot_2024-07-24-00-29-26-211_com.follow.clash-edit.jpg](https://github.com/user-attachments/assets/8a476f0b-ea45-45d7-a11a-1fac1f135d3e)

**Comment by PctAIGM** [comment]
先增加规则：GEOSITE,speedtest,PROXY 
PROXY根据机场的proxy-group设置

**Comment by xjbc123** [comment]
我是手机版，请问从哪设置。

**Comment by xjbc123** [comment]
只有订阅，不会规则，我还是等更新吧，不过不支持speedtest 的客户端还是头一次见。

PctAIGM ***@***.***> 于 2024年7月26日周五 下午2:39写道：

**Comment by PctAIGM** [comment]
或者你先开全局模式测速试试

**Comment by chen08209** [comment]
app是否走代理，取决于规则
