### ISSUE TITLE
无法修改【禁用规则】规则，例如禁止ADOBE软件的联网功能！

### ISSUE THREAD

**Issue by qq11109071** [chen08209/FlClash#155]
- DOMAIN-KEYWORD,adobe,🛑 全球拦截
- DOMAIN-SUFFIX,adobe.io,🛑 全球拦截
-想添加以上两条规则到Rule list
![Snipaste_2024-07-24_10-44-03](https://github.com/user-attachments/assets/4768810e-ad57-48f2-b3ad-e23b269c8cf8)
以上内容只可以查看，但添加不了规则，建议以后更新，谢谢！

**Comment by yifai** [comment]
麻烦看看clash的wiki，用机场订阅无法修改的，改了也没用，更新就没有了。

**Comment by qq11109071** [comment]
我知道更新后是没有了。但不更新是不是依然是存在的。再说更新也不怕。我写的有脚本呢。

**Comment by yifai** [comment]
> 我知道更新后是没有了。但不更新是不是依然是存在的。再说更新也不怕。我写的有脚本呢。
> 
> 
手机版用订阅是无法修改的，要改就用proxy-providers自定义规则。

**Comment by qq11109071** [comment]
请问有什么办法可以禁止关键词，如下：
DOMAIN-KEYWORD,adobe,🛑 全球拦截
DOMAIN-SUFFIX,adobe.io,🛑 全球拦截
哪个软件可以做得到，谢谢

**Comment by yifai** [comment]
> 请问有什么办法可以禁止关键词，如下：
> DOMAIN-KEYWORD,adobe,🛑 全球拦截
> DOMAIN-SUFFIX,adobe.io,🛑 全球拦截
> 哪个软件可以做得到，谢谢
> 
电脑端可以用脚本或merge ，手机无法用吧，都说了自定义规则就可以
https://wiki.metacubex.one/example/conf/

**Comment by qq11109071** [comment]
不懂怎么处理。。。

**Comment by yifai** [comment]
看Wiki或其它自定义配置教程

**Comment by Waitung** [comment]
把自动更新关了就可以修改了

**Comment by yifai** [comment]
> 把自动更新关了就可以修改了

这样的话，机场配置有更改，你就用不了。一更新了，修改的又没有了，还是自定义配置吧

**Comment by qq11109071** [comment]
建议软件加这样的功能！可以额外添加配置功能（或插件、或脚本）！

**Comment by txyyh** [comment]
@qq11109071 请不要无故@贡献者，我就写了个github action我能改啥

**Comment by qq11109071** [comment]
> @qq11109071 请不要无故@贡献者，我就写了个github action我能改啥

我这是有问题要反馈，什么叫“不要无故@贡献者”？github是一个公共开放的沟通平台。官方都没有禁止这样的功能，你凭什么让别人闭嘴？都来儿这了，不要见人还是想着“你要向别人下跪”，还是“别人要向你下跪”！自由交流，公开发言，向大家请教问题，向作者反应问题，有何不妥，什么叫无故@别人？

**Comment by AquaSimulacra** [comment]
你提的不是issue而是enhancement，开发者完全可以不理你。
