### ISSUE TITLE
[功能请求] 增加“关闭全部连接”选项

### ISSUE THREAD

**Issue by pasical** [chen08209/FlClash#158]
在切换节点后有的连接不会自动刷新，依然使用原来的节点。（PC版，开启tun）同时手动关闭连接过于频繁会导致软件崩溃，所以希望增加一键关闭全部连接功能。

**Comment by MarkIvory2973** [comment]
赞同

**Comment by efaun** [comment]
现在支持了
![QQ_1721985594528](https://github.com/user-attachments/assets/75b83c38-499a-412a-88ce-79021139a574)

**Comment by pasical** [comment]
最新版已更
