### ISSUE TITLE
【功能】更便捷的导入配置方式

### ISSUE THREAD

**Issue by MarkIvory2973** [chen08209/FlClash#159]
1. 文件拖拽导入
2. 截屏二维码导入（和 V2RayN 一样）
3. 文件粘贴导入（在配置页按下Ctrl+V导入文件）
4. URL粘贴导入（在配置页按下Ctrl+V导入链接）

只是一些建议，选择性地添加功能。

**Comment by chen08209** [comment]
这些暂时都不会考虑
