### ISSUE TITLE
分流列表添加搜索功能

### ISSUE THREAD

**Issue by Chuyiyue** [chen08209/FlClash#16]
希望分流选择列表添加搜索应用的功能，方便搜索应用和包名
![Screenshot_2024-06-06-10-22-31-947_com.follow.clash-edit.jpg](https://github.com/chen08209/FlClash/assets/92413270/4ea3a445-5492-47c0-be82-d542e793c3bb)

![IMG_20240606_102333.jpg](https://github.com/chen08209/FlClash/assets/92413270/a329ea73-aac0-48cd-9a01-9cadd3450d5d)

![IMG_20240606_102400.jpg](https://github.com/chen08209/FlClash/assets/92413270/b775175c-3a80-4044-b35e-567b52d1cf71)

**Comment by chen08209** [comment]
好的，计划中
