### ISSUE TITLE
恢复配置错误

### ISSUE THREAD

**Issue by lag930518** [chen08209/FlClash#163]
备份与恢复，可以备份数据到WebDAV，但是恢复数据的时候提示错误
![微信图片_20240726081953](https://github.com/user-attachments/assets/975f8cfa-e15f-495d-bac2-a22fa785280c)

**Comment by Mcayear** [comment]
遇到了同样的问题

**Comment by chen08209** [comment]
备份和恢复相关有较大改动，由于这个部分不只是取决于客户端，无法复现解决，暂时关闭了，自行测试
