### ISSUE TITLE
不支持hy2节点吗？

### ISSUE THREAD

**Issue by loveznk** [chen08209/FlClash#165]
同是Clash Meta内核，相同的订阅规则，CMFA能够识别hy2节点，Flclash却不识别hy2节点，是还没有支持hy2节点吗？

**Comment by loskyertt** [comment]
是可以支持的

**Comment by loveznk** [comment]
> 是可以支持的

但是同一个订阅链接，我用CMFA能够识别出的hy2节点，为什么用Flclash却没有呢？

**Comment by shebing5** [comment]
转化为base64订阅，我的可以

**Comment by Kia678** [comment]
> > 是可以支持的
> 
> 但是同一个订阅链接，我用CMFA能够识别出的hy2节点，为什么用Flclash却没有呢？

Flclash的默认user-agent有问题，导致订阅下发之前的UA识别有问题

**Comment by loveznk** [comment]
> > > 是可以支持的
> > 
> > 
> > 但是同一个订阅链接，我用CMFA能够识别出的hy2节点，为什么用Flclash却没有呢？
> 
> Flclash的默认user-agent有问题，导致订阅下发之前的UA识别有问题


> > > 是可以支持的
> > 
> > 
> > 但是同一个订阅链接，我用CMFA能够识别出的hy2节点，为什么用Flclash却没有呢？
> 
> Flclash的默认user-agent有问题，导致订阅下发之前的UA识别有问题

意思是我需要自己修改Flclash的user-agent才能识别出hy2节点，对吗？

**Comment by loskyertt** [comment]
> > 是可以支持的
> 
> 但是同一个订阅链接，我用CMFA能够识别出的hy2节点，为什么用Flclash却没有呢？

这个其实得看机场的订阅链接形式，你需要复制clashmeta的订阅链接然后导入，普通的订阅链接（像clash verge rev能识别）flclash可能只能解析出配置，但是不能加载节点。我遇到的情况是这样并解决的![Screenshot_2024-07-31-01-58-11-433_com.follow.clash.jpg](https://github.com/user-attachments/assets/480aec3a-82ac-4af5-9a1b-1ae557c40e8e)

**Comment by loveznk** [comment]
> > > 是可以支持的
> > 
> > 
> > 但是同一个订阅链接，我用CMFA能够识别出的hy2节点，为什么用Flclash却没有呢？
> 
> 这个其实得看机场的订阅链接形式，你需要复制clashmeta的订阅链接然后导入，普通的订阅链接（像clash verge rev能识别）flclash可能只能解析出配置，但是不能加载节点。我遇到的情况是这样并解决的![Screenshot_2024-07-31-01-58-11-433_com.follow.clash.jpg](https://private-user-images.githubusercontent.com/123556145/353565350-480aec3a-82ac-4af5-9a1b-1ae557c40e8e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MzAyMzMsIm5iZiI6MTcyMjQyOTkzMywicGF0aCI6Ii8xMjM1NTYxNDUvMzUzNTY1MzUwLTQ4MGFlYzNhLTgyYWMtNGFmNS05YTFiLTFhZTU1N2M0MGU4ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQxMjQ1MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjY5MmY3YWI5ZjdiMTAyM2Y4ODI2MThlNDM5Njg3NTA4MWI5MjM1MjlmOTBjNmVkNjEzNDNhNWUyNDVlNTVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vDvg1JZDn-clx760gMVHLyjSU0TlGp82sQayheh4OEM)

谢谢解答，但是我的机场里面只有clash订阅链接，没有clash meta订阅链接，唉！

**Comment by loveznk** [comment]
在节点选择页面，我的订阅链接里面有2条hy2节点，Flclash就显示过滤掉2条线路，真搞不懂了。

**Comment by chen08209** [comment]
支持，节点中如果没有hy2节点，可以考虑修改ua或者联系机场分发

**Comment by sdgsgsdf** [comment]
> 转化为base64订阅，我的可以

base64订阅支持吗？我的一个订阅就是base64，但是添加订阅直接报错说无法识别
