### ISSUE TITLE
点击开始按钮无反应，不进行代理

### ISSUE THREAD

**Issue by LeslieLee0420** [chen08209/FlClash#167]
![S40728-20322440_com follow clash](https://github.com/user-attachments/assets/c807abd7-dd8a-4a06-acb3-7f58259f3fd5)
设备魅族21 pro，系统flyme11。
点击开始按钮没有反应，运行时间一直是0，也没有弹出允许app连接vpn选项。

**Comment by LeslieLee0420** [comment]
找到原因了……

**Comment by wolaijiuni** [comment]
> 找到原因了……

老哥 什么原因  我也遇到了

**Comment by LeslieLee0420** [comment]
> > 找到原因了……
> 
> 老哥 什么原因 我也遇到了

去系统设置里，找vpn页面，我是把之前用的cmfa设置了始终保持vpn连接，关掉这个就好了。
