### ISSUE TITLE
v0.8.49更新后不支持从分身导入了, 之前还支持, 编辑也报错找不到文件

### ISSUE THREAD

**Issue by efaun** [chen08209/FlClash#177]
![1722447983366](https://github.com/user-attachments/assets/0b0948f7-0a6f-45f2-947f-ebdde8c83f24)
![1722448006357](https://github.com/user-attachments/assets/5dedd5e7-9cc1-4e8a-8206-272498566daa)

**Comment by chen08209** [comment]
没有这个使用场景，短时间应该没法处理
