### ISSUE TITLE
配置界面UI优化提议

### ISSUE THREAD

**Issue by Chuyiyue** [chen08209/FlClash#18]
新增显示配置类型，到期时间，以及优化显示布局，顶栏新增一键更新所有配置按钮

显示效果如附件图片所示

<img width="540" alt="无标题" src="https://github.com/chen08209/FlClash/assets/92413270/bdcf59a3-22d9-4c93-994b-955d8d6133b9">

**Comment by chen08209** [comment]
偷了

**Comment by Chuyiyue** [comment]
![Screenshot_2024-06-07-11-40-26-989_com getsurfboard-3](https://github.com/chen08209/FlClash/assets/92413270/560ee78f-ae73-4e9b-9391-827c5ab05755)

**Comment by TingTing1990** [comment]
目前配置文件好像只能编辑文件名，不能编辑里面的内容
