### ISSUE TITLE
为 Android 端的应用访问控制功能加入列表排序

### ISSUE THREAD

**Issue by goddaneel** [chen08209/FlClash#180]
因为要在白名单模式下代理 google play 服务，所以开启了“显示系统软件”。但这样导致应用列表极为混乱，必须通过搜索才能找到目标软件。
希望可以为应用列表加入排序功能，类似 clash meta for android 那样，可以通过名称、安装时间等进行升序降序排列。

**Comment by fuwuqi298** [comment]
加一个

建议弄两个一级菜单，选中的放到菜单下去，就分组一下。

现在选中的在前面显示，未选中的在后面显示，比较乱
@chen08209

**Comment by goddaneel** [comment]
新版本加入了排序功能，但实际效果有问题。

这是我手机实际的安装时间顺序：
![Screenshot_2024-08-18-18-03-20-37.jpg](https://github.com/user-attachments/assets/df6dad6a-76ab-4b25-807e-84cfcad4467a)

这是flclash开启“时间”排序后的效果：
![Screenshot_2024-08-18-18-05-53-64.jpg](https://github.com/user-attachments/assets/4d0ce1eb-491b-409e-ba7e-1e68a084d5c5)

另外，如果系统软件也显示的话，第三方软件会在最底部，需要划很久，倒序很有必要。
