### ISSUE TITLE
FlClash-0.8.49-android-armeabi-v7a安装到电视上，添加订阅超级难用

### ISSUE THREAD

**Issue by myvmiao** [chen08209/FlClash#182]
可以说在电视上根本无法输入订阅链接，一个一个遥控器按键输入，太痛苦了，希望增加手机扫码等其他方式，添加订阅

**Comment by hujuying** [comment]
貌似基本上不是tv版都这个毛病，所以我一般都用无线鼠标控制。

**Comment by chen08209** [comment]
目前没有tv设备

**Comment by titizh** [comment]
你们是怎么控制光标到菜单上的啊？我只能在主页面移动，没法到边上的菜单啊…… :-(

**Comment by work-chausat** [comment]
一打开软件就立即懵逼，出来一个免责声明的窗口挡在前面遥控器怎么弄都关不掉，啥都操作不了
