### ISSUE TITLE
[BUG]添加的订阅timeout

### ISSUE THREAD

**Issue by xingxin1590** [chen08209/FlClash#186]
在verge上的同一个订阅正常，flcalsh上显示timeout，重导，更新订阅都无效果
并且这是普遍现象，有些订阅的节点会在flclash显示timeout，但是在其他代理软件是正常延迟连接
![image](https://github.com/user-attachments/assets/b09f7d59-58b1-417e-a6d8-41eb555560b4)
![image](https://github.com/user-attachments/assets/f061ab19-4c68-4404-a5f2-e5d70b02443f)

**Comment by Kafurtan** [comment]
同上， TimeoutException after 0:00:10.000000: Future not completed

**Comment by zhaocai** [comment]
同问，下次还是发布之后等几天再更新

**Comment by chen08209** [comment]
延迟测试超时时长为5s，目前占时不支持自定义超时时长，可以尝试更换测速链接

**Comment by linZsama** [comment]
> 同上， TimeoutException after 0:00:10.000000: Future not completed

解决了吗请问
