### ISSUE TITLE
[BUG]隐藏后台之后会导致断流和IP检测timeout

### ISSUE THREAD

**Issue by xingxin1590** [chen08209/FlClash#188]
开启隐藏后台功能后会导致断流和timeout，需要重新打开并点击代理页面才会自动选择生效
![IMG_20240802_233642.jpg](https://github.com/user-attachments/assets/2d130906-9bfc-4d5e-9ba1-b0b6b55525c7)

**Comment by chen08209** [comment]
无法复现

**Comment by xingxin1590** [comment]
> 无法复现
IP检测timeout确实常有，断流少
