### ISSUE TITLE
【仅代理】模式竟然藏得这么深

### ISSUE THREAD

**Issue by Blood3C** [chen08209/FlClash#189]
之前一直以为仅有【系统代理】和【tun】模式，现在才知道打开Flclash不点击仪表盘的启动按钮，默认就是【仅代理】模式

**Comment by wenliyang** [comment]
https://github.com/chen08209/FlClash/issues/98#issuecomment-2212874416

不是软件不支持，只是实现方式比较特别

**Comment by Blood3C** [comment]
> [#98 (comment)](https://github.com/chen08209/FlClash/issues/98#issuecomment-2212874416)
> 
> 不是软件不支持，只是实现方式比较特别

看到之前的评论懂了，打开Flclash不点击仪表盘的启动按钮  默认就是【仅代理】模式

**Comment by hujuying** [comment]
clash核心都是这样。一般启动了clash就开始代理了。

**Comment by okFancy** [comment]
是的我一度以为这软件没法使用，鼓捣一会才发现有个启动按钮
