### ISSUE TITLE
Android 设置 doh 会影响 flclash 嘛？

### ISSUE THREAD

**Issue by yixiuge301** [chen08209/FlClash#190]
最近发现手机有 dns 劫持的情况，某些网站打不开，还不是被强的域名。

在手机设置里设置了 doh 后，就没发生了。

咨询一下手机设置 doh 会不会影响 flclash？因为之前用 cfw，有在他的 issue 中看到 windows 设置 doh 会影响 cfw。

**Comment by weduolijia** [comment]
实验过了安卓dot会把flclash节点DNS覆盖掉，其实也无伤大雅。

**Comment by yixiuge301** [comment]
应该不是 dns 的问题，是运营商的问题，流量会打不开，wifi 可以，都是电信。

看了 dns 解析出的地址是对的。
