### ISSUE TITLE
希望在WebDAV备份时加入打包压缩和AES加密

### ISSUE THREAD

**Issue by EX-XD** [chen08209/FlClash#191]
压缩可以显著减少空间占用及传输时间，AES加密能增强安全性，现在配置文件明文放服务器我觉得不安全，特别是为了同步速度会选择一些大厂的WebDAV，配置文件明文放里面我不放心。

**Comment by chen08209** [comment]
WebDAV目前已经通过压缩处理，但是应该不会考虑加密
