### ISSUE TITLE
win10 任务栏图标右键更改出站模式无效

### ISSUE THREAD

**Issue by wkhkh** [chen08209/FlClash#192]
win10 任务栏图标右键更改出站模式无效,只有在仪表盘更改才生效

**Comment by chen08209** [comment]
无法复现，需要更详细的说明，比如录屏

**Comment by wkhkh** [comment]
> 无法复现，需要更详细的说明，比如录屏

https://github.com/user-attachments/assets/e756d3d0-0387-499f-ab12-d78bd6357f04

就像这样

**Comment by wkhkh** [comment]
@chen08209
