### ISSUE TITLE
希望在桌面端任务栏图标右键中加入开关tun模式

### ISSUE THREAD

**Issue by 96368a** [chen08209/FlClash#193]
希望在桌面端任务栏图标右键加入开关tun模式，主要是我日常开关tun模式比较频繁，每次都要点开gui界面再操作有点麻烦

**Comment by zhouxinghong** [comment]
最好加在这里
![image](https://github.com/user-attachments/assets/14304237-537e-4bed-a8f9-85ada7070f5c)
