### ISSUE TITLE
在“托盘图标是否显示到任务栏”的设置中会不断创建新项目，导致旧的“显示到任务栏”设置失效。

### ISSUE THREAD

**Issue by zanghuaren** [chen08209/FlClash#194]
我希望在任务栏中显示软件图标而不是托盘中，但总会创建新项目导致设置失效。
![image](https://github.com/user-attachments/assets/43ec6bcc-7e91-45fc-b65d-8b8c46b4b9aa)
![image](https://github.com/user-attachments/assets/16a274b5-7ffc-42a3-b297-7eaad2935d1f)
不知道该如何解决。

**Comment by chen08209** [comment]
无法复现，目前应该是不同目录下的FlClash都会创建不同的图标，找到正确的FlClash的图标，然后拖拽或者手动打开显示托盘的选项，无论是关闭应用启动，开始开机自启，应用的托盘都能自动显示在外部

**Comment by zanghuaren** [comment]
好的，问题已解决，原来可以直接拖拽。谢谢。

**Comment by zanghuaren** [comment]
> 无法复现，目前应该是不同目录下的FlClash都会创建不同的图标，找到正确的FlClash的图标，然后拖拽或者手动打开显示托盘的选项，无论是关闭应用启动，开始开机自启，应用的托盘都能自动显示在外部

经过几天的测试，我发现即使使用拖拽，也还是会常常失效，这种情况最近大概出现了四五次。
我用的最新版的flclash，并且尝试卸载重装，也无法解决问题。我不清楚这是否和win11的bug有关，我使用的是最新版的win11，在提交这个Issues前，因为别的原因我曾重装系统，也依然会出现这种情况。换句话说，可以认为我可以复现这个问题。

**Comment by zanghuaren** [comment]
补充：的确每次失效都是因为创建一个新图标，
<img width="296" alt="Snipaste_2024-08-11_16-02-20" src="https://github.com/user-attachments/assets/e013c0a0-9ede-407a-97dd-83613576b87f">
上图为刚拖拽出来后以及重启后的情况。
