### ISSUE TITLE
0.8.51增加了本地备份功能非常不错。但是0.8.51有一个问题，恢复网络备份会报错。回退到0.8.50版本使用恢复网络备份就没有问题，不知道大家有没有遇到过？

### ISSUE THREAD

**Issue by iD2073** [chen08209/FlClash#198]
![mmexport1722947391089.jpg](https://github.com/user-attachments/assets/e2a3b8a1-f834-4412-907a-48a9ce8712ac)

这是出现问题时的截图！

**Comment by chen08209** [comment]
新版本备份方面有改动，不兼容旧版本
