### ISSUE TITLE
下一版会跟进最新内核吗？

### ISSUE THREAD

**Issue by a185039136** [chen08209/FlClash#2]
RT;下一版会跟进最新内核吗？

**Comment by chen08209** [comment]
目前的主分支内核版本与clash meta的meta分支差距应该不到两个月，dev分支已经同步最近更新，但是不确定什么时候会发版。
后续关于内核的同步，会尽量保持在两个月以内，如果有比较实用或者需求比较大的新功能，会及时同步。
