### ISSUE TITLE
桌面端UI的若干问题

### ISSUE THREAD

**Issue by YanBai233** [chen08209/FlClash#20]
# 桌面端UI的若干问题

版本号：0.8.12

## 一、代理界面
**问题表现：**
- 多规则选择时，如果规则过多超过窗口显示数量，顶部横条无法通过滑动来选择规则

![image](https://github.com/chen08209/FlClash/assets/54111576/1e05da76-1eba-4f51-9876-2274661bf696)

## 二、主题选项卡
**问题表现：**
- 设置-主题-主题色彩
- 主题色彩只能显示前三种配色，后面的配色方案无法显示，且无法通过滑动来选择规则

![image](https://github.com/chen08209/FlClash/assets/54111576/6be5acf6-06d7-478a-84ac-27a135253a0f)

## 三、字体
**问题表现：**
- 中文字体部分显示异常
- 表现为单个字过粗；异体
- 移动端字体显示正常

![image](https://github.com/chen08209/FlClash/assets/54111576/d5b7631f-0d4a-436c-94ab-7b20ccd6b082)
![image](https://github.com/chen08209/FlClash/assets/54111576/fa76390b-d4e5-4633-ae32-b1cbe4294a25)
![image](https://github.com/chen08209/FlClash/assets/54111576/40968c8a-3745-4177-8bea-24d2af2b3e05)

**Comment by chen08209** [comment]
横向滚动可通过shift+鼠标滚动实现，出于美观度考虑暂时应该不会添加滚动条。
字体方面，客服端语言为中文，在win10或者win11默认情况下，一般是正常，更多问题有待后续解决。

**Comment by YanBai233** [comment]
> 横向滚动可通过shift+鼠标滚动实现，出于美观度考虑暂时应该不会添加滚动条。 字体方面，客服端语言为中文，在win10或者win11默认情况下，一般是正常，更多问题有待后续解决。

横向滚动能否增加一个鼠标拖拽滑动，可能会更直观和方便

**Comment by chen08209** [comment]
> > 横向滚动可通过shift+鼠标滚动实现，出于美观度考虑暂时应该不会添加滚动条。 字体方面，客服端语言为中文，在win10或者win11默认情况下，一般是正常，更多问题有待后续解决。
> 
> 横向滚动能否增加一个鼠标拖拽滑动，可能会更直观和方便

之后有时间应该可能会尝试实现

**Comment by chen08209** [comment]
桌面端已支持鼠标拖拽滚动
