### ISSUE TITLE
仪表盘国旗ip显示异常

### ISSUE THREAD

**Issue by Meow7575** [chen08209/FlClash#201]
仪表盘的国旗和ip有时会选取到其他国家的，需要重新切换才正常

**Comment by chen08209** [comment]
需要更多描述

**Comment by dyphire** [comment]
打开 ipv6 后我可以复现它，仪表盘国旗 ip 显示不正确。ipv4 下正常
![image](https://github.com/user-attachments/assets/6e891905-56f0-4302-b77b-1d7564b6fdc7)
我的代理节点中没有对应仪表盘显示的国旗的相关节点，查看请求和连接也没有对应国旗 ip 的记录，应该是 flclash 显示错误

**Comment by dyphire** [comment]
@chen08209 请考虑重新打开这个 issue，它没有被修复，我已经给出了具体的描述
