### ISSUE TITLE
[功能请求]需要广告阻止功能

### ISSUE THREAD

**Issue by gov360** [chen08209/FlClash#206]
因为有的订阅链接里面包含广告阻止规则，而有的不包含相关的资源规则，故希望可以通过附加的形式加入相应的广告阻止规则来规避广告

**Comment by gov360** [comment]
当然可能还可以通过替换具有广告阻止功能的DNS地址来实现广告阻止功能，也许这种方法更简单粗暴，但是对本地资源的消耗应该是比较低的

**Comment by Meow7575** [comment]
你说的全都可以靠配置文件实现

**Comment by chen08209** [comment]
可以通过配置一定程度上实现，暂时没有相关计划
