### ISSUE TITLE
安卓端请求添加功能

### ISSUE THREAD

**Issue by MarvelousTune** [chen08209/FlClash#21]
![Screenshot_20240608_111629_One UI Home](https://github.com/chen08209/FlClash/assets/40261598/5d038b5e-18e0-4f2b-8b16-df2e3fdacc0c)
这样的shortcut 可以拉到桌面上 快速启动

**Comment by chen08209** [comment]
已经有磁贴了，只有一个快捷方式的情况下，基本相当于上位替代。
