### ISSUE TITLE
rule-proviedes无法加载

### ISSUE THREAD

**Issue by Become-ILLUSORY** [chen08209/FlClash#212]
使用了meta的配置文件格式，配置文件当中包含了rule-providers，但是其中的外部资源部分无法加载到flclash的  工具   资源  当中![IMG_20240810_151034.jpg](https://github.com/user-attachments/assets/0a8fccb8-a1f9-4c70-88c1-8ce6db12e8d1)

![IMG_20240810_150904.jpg](https://github.com/user-attachments/assets/b5f577e8-9a3a-430b-8f6b-03c5ff64a2c6)

**Comment by chen08209** [comment]
新版本已修复

**Comment by Become-ILLUSORY** [comment]
> 新版本已修复

更新了，但是  工具  资源  里仍然只有4个，分别是geoip，geosite，mmdb，asn，并没有我的配置文件里写的rule-providers

**Comment by wolaijiuni** [comment]
> > 新版本已修复
> 
> 更新了，但是 工具 资源 里仍然只有4个，分别是geoip，geosite，mmdb，asn，并没有我的配置文件里写的rule-providers

老哥  解决了吗     我也遇到了
