### ISSUE TITLE
ArchLinux无法直接上传配置文件

### ISSUE THREAD

**Issue by xqiangne** [chen08209/FlClash#213]
添加配置选择直接上传配置文件提示：Exception: Couldn't find the executable zenity in the path.

**Comment by Saplyn** [comment]
I'm using Manjaro (Arch-based distro) and resolved this issue by manually installing `zenity` the executable. I'm using `pamac`:

```bash
sudo pamac install zenity
```

**Comment by xqiangne** [comment]
> 我使用的是Manjaro（基于Arch的发行版），可以通过手动安装`zenity`来解决这个问题。我用的是`pamac`：
> 
> ```shell
> sudo pamac install zenity
> ```
> 
> 我正在使用 Manjaro（基于 Arch 的发行版），并通过手动安装`zenity`可执行文件解决了此问题。我正在使用`pamac`：
> 
> ```shell
> sudo pamac install zenity
> ```

**Comment by xqiangne** [comment]
> > 我使用的是Manjaro（基于Arch的发行版），可以通过手动安装`zenity`来解决这个问题。我用的是`pamac`：
> > ```shell
> > sudo pamac install zenity
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我正在使用 Manjaro（基于 Arch 的发行版），并通过手动安装`zenity`可执行文件解决了此问题。我正在使用`pamac`：
> > ```shell
> > sudo pamac install zenity
> > ```

好的，多谢。
