### ISSUE TITLE
部分组件取色修改

### ISSUE THREAD

**Issue by KustuTear** [chen08209/FlClash#214]
![IMG_20240811_141900.jpg](https://github.com/user-attachments/assets/ee14affb-3780-4baf-bfea-d2394acfb46b)

![IMG_20240811_141846.jpg](https://github.com/user-attachments/assets/888f801a-77da-4a56-aa08-74343554371a)

![IMG_20240811_141818.jpg](https://github.com/user-attachments/assets/4ddfe84d-abf0-4e01-913a-4d67629c0871)

如图三个功能性按钮，亮色模式下采用浅色调按钮会有种突兀感

改成使用深色调观感会更好些

**Comment by chen08209** [comment]
符合material you 设计规范，暂时不考虑更改
