### ISSUE TITLE
延迟排序

### ISSUE THREAD

**Issue by tangwenlongNO1** [chen08209/FlClash#217]
每次测速完或者更新以及切换订阅后代理不会按照延迟排序，参考surfboard

**Comment by weduolijia** [comment]
这玩意不是可以手动调整么

**Comment by chen08209** [comment]
无法复现，录屏或者其他更详细的描述

**Comment by tangwenlongNO1** [comment]
https://github.com/user-attachments/assets/1e3426ec-c181-49d2-a5d3-aca81b83c0d7

前面是flclash后面是surfboard @chen08209
