### ISSUE TITLE
鸿蒙Next版本可以考虑一下

### ISSUE THREAD

**Issue by liu798675179** [chen08209/FlClash#219]
纯血鸿蒙目前还没有这方面的app，可以抢占高地

**Comment by LonHon** [comment]
好好好  自己往枪口上撞是吧

**Comment by Ervoconite** [comment]
鸿蒙可以安装未知来源吗？鸿蒙开发者工具会不会审查你的代码来确定你做的是什么？
答案是很有可能会。

**Comment by zblmsph** [comment]
next都要在系统级webview塞审查，这种玩意想啥呢

**Comment by zblmsph** [comment]
![屏幕截图 2024-08-21 081740](https://github.com/user-attachments/assets/667d8280-e889-47f3-9109-6bc0155609f6)


> next都要在系统级webview塞审查，这种玩意想啥呢

**Comment by Leard-K** [comment]
我现在4.2的版本就装不上了，咋办？是安装x86_64版本的apk吧？

**Comment by chen08209** [comment]
不考虑
