### ISSUE TITLE
安装新版本时提示要卸载新版本，不能覆盖安装吗

### ISSUE THREAD

**Issue by AutumnMengyun** [chen08209/FlClash#222]
如题

**Comment by chen08209** [comment]
需要详细描述平台，目前我这里测试是都可以覆盖安装的了

**Comment by 1115419568** [comment]
> 需要详细描述平台，目前我这里测试是都可以覆盖安装的了

您好，收到我的回复了吗

**Comment by chen08209** [comment]
如题版本不一致，可能是安装不同来源的版本导致，正常时可以覆盖安装的

**Comment by AutumnMengyun** [comment]
> 如题版本不一致，可能是安装不同来源的版本导致，正常时可以覆盖安装的

我都是从GitHub下载的安装包
