### ISSUE TITLE
建议长按配置列表项后可以拖动排序

### ISSUE THREAD

**Issue by gituser056391** [chen08209/FlClash#229]
就是自定义拖动排序订阅源，之前很希望cfa和cmfa实现的功能，现在看来只有寄希望于这里了，感谢～

**Comment by gituser056391** [comment]
同时希望自定义的排序可以通过webdav同步到其他flclash客户端

**Comment by EX-XD** [comment]
附议。
本人配置文件有点多且杂乱，希望能有自定义排序或者按名称排序，谢谢
