### ISSUE TITLE
安卓端三大金刚键的颜色显示不正常

### ISSUE THREAD

**Issue by gituser056391** [chen08209/FlClash#230]
澎湃OS，安卓14，如图，希望能修复成正常颜色（黑色）
![Screenshot_2024-08-14-18-58-54-278_com.follow.clash-edit.jpg](https://github.com/user-attachments/assets/2dcf5bdb-7167-4821-bef9-f5d5d7b18396)

**Comment by chen08209** [comment]
新版本已解决
