### ISSUE TITLE
[Bug]备份与回复无法使用（本地端）

### ISSUE THREAD

**Issue by rucifa** [chen08209/FlClash#235]
我使用本地端的备份，明明窗口跳出来备份成功
但是到指定的位置内却没找到该备份文件

但是使用WebDAV备份到PCloud，确有正常资料备份成功
请再确认看看

我的环境
Windows 11(Home、Pro) 2023H2

**Comment by din1028** [comment]
同样的问题

**Comment by chen08209** [comment]
新版本已解决
