### ISSUE TITLE
[feature] 配置 `自动选择` 的规则时手动测试后选择更低延迟节点并保持

### ISSUE THREAD

**Issue by YuHuanTin** [chen08209/FlClash#239]
手动选择延迟较高的节点，然后使用`测试延迟`按钮或者重新连接节点均不能切换连接到延迟最低的节点
![PixPin_2024-08-16_08-59-36](https://github.com/user-attachments/assets/d2f61330-4b52-4433-af56-1a94e8465a39)

**Comment by muyicn** [comment]
同样的问题。。。

**Comment by xiaozhidepikaqiu** [comment]
我也遇到了这个问题，我是安卓版的。
自动选择没生效，过一段时间回到软件查看的时候节点总是选择默认的第一个，不知道怎么办。
