### ISSUE TITLE
跟surfboard一模一样？

### ISSUE THREAD

**Issue by xmengnet** [chen08209/FlClash#241]
![IMG_20240816_125001.jpg](https://github.com/user-attachments/assets/ebbb0d89-a623-45eb-b509-3644e533afb8)

这是谁抄的谁啊

**Comment by Ervoconite** [comment]
抄的surfboard吧，但是比surfboard多很多支持。
非盈利软件，就别这么在意设计上的雷同了，而且也并不完全相同。

**Comment by Ervoconite** [comment]
我之前也是surfboard，但是不跨平台，不支持新协议，经常报不识别订阅的错误，才转flclash的，目前来看，功能上相当nice，跨平台做的也很好。

**Comment by Natural-selection1** [comment]
如以上这位老哥说的 , 既然有改进 , 那么就算不是 "照抄" , 毕竟开源的意义就是 "不断地迭代"

**Comment by Erven2016** [comment]
都是用的 Material Design 3，设计语言相近，懒得弄界面设计，借鉴一下没啥问题（同类软件有 surfboard 这个现成界面方案），这个项目也是开源的。如果你有更好的设计方案，可以贡献代码

**Comment by HozumiMoa** [comment]
只是抄ui罢了，这俩内核都不一样

**Comment by 18333647901** [comment]
> 如以上这位老哥说的 , 既然有改进 , 那么就算不是 "照抄" , 毕竟开源的意义就是 "不断地迭代"

嗯 我有个疑问 surfboard的仓库呢？怎么搞了个tv的版本了，我一升级原本的软件没了😓
