### ISSUE TITLE
右下角启动按键不见了

### ISSUE THREAD

**Issue by Tuuu5659** [chen08209/FlClash#246]
![微信图片_20240816212212](https://github.com/user-attachments/assets/a2575b28-7eb1-48dc-b898-25a4eec9fc1f)
之前装好卸载过一次，卸载后就这样了，没启动按键。甚至重装了个电脑系统， 安装版或者便携版，依然都没有启动按键了，麻烦各位大佬看一下

**Comment by okFancy** [comment]
真实原因是配置的代理没有了，重启应用会丢失不保存。感觉还是不问题，bug太多
![image](https://github.com/user-attachments/assets/2229698b-1348-4f9f-9653-1e79105fade9)
