### ISSUE TITLE
Improve font-weight to enhance text readability.

### ISSUE THREAD

**Issue by cyanray** [chen08209/FlClash#248]
Some text (As shown in screenshot, "Selector · ...") appears with a font-weight that is too thin, making it difficult to read on my 1080P monitor, especially for Chinese characters.

Could you consider increasing the font-weight for these texts, or perhaps provide an option to customize the font?

In screenshot, the text appears clearer, possibly due to compression making the font appear thicker.

部分文字的字体粗细太细了，在1080P的显示器上难以阅读，尤其是中文字符。

能否考虑增加这部分字体的粗细？或者提供选项来自定义字体？

截图没能反映真实观感，可能是压缩的原因字体粗细变粗了，显得更清晰了。

![screenshot](https://github.com/user-attachments/assets/e0ddf2b0-0132-422f-a577-8e8fcef645e2)

**Comment by chen08209** [comment]
新版本可以使用内置字体
