### ISSUE TITLE
关于vivopad通讯共享与vpn同时开启时网络无法使用的问题

### ISSUE THREAD

**Issue by YanBai233** [chen08209/FlClash#25]
# vivopad通讯共享与vpn同时开启时网络无法使用 #
软件版本：0.8.19
设备：vivoX100s、vivo Pad3 Pro
设备系统：originOS4 与 OriginOS4 HD（全版本号均存在该问题）
涉及系统功能：多设备互联-通讯共享（出现在vivopad上）
## 问题描述 ##
更新FlClash（0.8.18→0.8.19）
vivoPad通过通讯共享使用手机流量，并开启FlClash系统代理后，网络不可用（包括国内流量）
全节点测速显示“Timeout”
## 问题排查 ##
**其他设备和软件**
- 手机在开启系统代理后不受影响
- 手机使用热点来向pad共享流量，恢复正常
- 退回0.8.18后，恢复正常
- 使用clash mate for android，代理和通讯共享工作正常
- 使用“冲浪板”、“clash for android”，代理和通讯共享工作正常
- 使用V2rayN，遇到与0.8.19一样的问题

**设置**
- 尝试关闭“允许应用绕过VPN”，问题依旧
- 更换“机场”，问题依旧
- 使用直连，问题依旧（未能访问国内网站）
- 开启“局域网代理”，问题依旧
- 更改端口，问题依旧
## 图片 ##
![Screenshot_20240611_103801](https://github.com/chen08209/FlClash/assets/54111576/60c5a969-b89a-48e7-8f04-17efe2727667)
![IMG_20240611_104013](https://github.com/chen08209/FlClash/assets/54111576/fe6e2248-3aff-4794-b65e-d6dc723dae84)

**异常的日志**
![Screenshot_20240611_104731](https://github.com/chen08209/FlClash/assets/54111576/00041575-49b6-48bb-ab0a-860c5ea8e818)
![Screenshot_20240611_104856](https://github.com/chen08209/FlClash/assets/54111576/c85c8555-5f47-4826-9f7b-d4e5a66b7965)

联系：yanbai_mail@qq.com

**Comment by chen08209** [comment]
18版本和19版本最大的区别就是打包使用的go版本不一样，如果排除偶然因素，之后应该会尝试解决。

**Comment by YanBai233** [comment]
在开启“访问控制-应用访问控制”后，恢复正常，问题解决。
