### ISSUE TITLE
代理面板的外部资源里的排序将外部代理改为置于最前而不是和外部规则一起按名称排序

### ISSUE THREAD

**Issue by dyphire** [chen08209/FlClash#250]
如题，目前代理面板的外部资源里的显示完全按名称排序，没有区分代理和规则的优先级。
外部代理应该始终置于最前而不是和外部规则混在一起按名称排序
![image](https://github.com/user-attachments/assets/5b20c5ee-d105-4ec1-addc-03c303a06c06)

就像 cfma 或其他 meta 内核的桌面 GUI 一样：
![image](https://github.com/user-attachments/assets/6ee02651-3639-430c-b00c-99a44baf1b33)

**Comment by chen08209** [comment]
新版本已解决
