### ISSUE TITLE
手动测延迟后，自动选择里面的节点无变动

### ISSUE THREAD

**Issue by Issac-Lee** [chen08209/FlClash#253]
发现flclash，手动测了延迟后，自动选择的节点并没有改变，必须等配置设置的测试间隔到了后自动测试延迟后，自动选择的节点才会根据新的延迟做变动。

**Comment by Ptilopsis01** [comment]
+1，希望能适配一下自动选择

**Comment by jk278** [comment]
同，不管测速还是更新，自动选择都没反应
