### ISSUE TITLE
切换全局模式后 节点和分组标签混在一起了

### ISSUE THREAD

**Issue by icowme** [chen08209/FlClash#257]
[
<img width="644" alt="2024-8-19 0-29-25" src="https://github.com/user-attachments/assets/125e1d20-0943-4f4a-991c-303cea416ffa">
](url)

切换全局模式后 节点和分组标签混在一起了
建议切换出站模式 规则/全局 代理节点还是按照原来的方式显示

**Comment by likaifenkeng** [comment]
支持。
