### ISSUE TITLE
我打开软件怎么是黑屏？

### ISSUE THREAD

**Issue by Deja-vuuu** [chen08209/FlClash#258]
<img width="796" alt="image" src="https://github.com/user-attachments/assets/49015259-0725-48d6-bc75-f2692482b176">
<img width="489" alt="image" src="https://github.com/user-attachments/assets/7063e043-97e3-4aeb-a78c-fee5ee1a95b1">

**Comment by GordonYoungCao** [comment]
我也是，你找到问题了吗？

**Comment by Deja-vuuu** [comment]
> 我也是，你找到问题了吗？

用不了 暂时放弃使用了

**Comment by chen-jingliang** [comment]
我也是，我系统是macos 15.1beta版。

**Comment by chen-jingliang** [comment]
更新：今天升级到了macos 15.1 beta3版本后，可以正常打开使用了。
