### ISSUE TITLE
 mac armd版本，重新应用后保存的配置项会丢失

### ISSUE THREAD

**Issue by okFancy** [chen08209/FlClash#259]
重启应用后配置的代理丢失，不保存。
![image](https://github.com/user-attachments/assets/2229698b-1348-4f9f-9653-1e79105fade9)

**Comment by wfs498121294** [comment]
你好  你的mac端能跑起来吗   我build libclash会报错  你那边会吗

**Comment by wangyingbo** [comment]
> 你好 你的mac端能跑起来吗 我build libclash会报错 你那边会吗

不用build，release页面有打包好的.dmg文件，直接下载安装就行。

**Comment by wangyingbo** [comment]
> 重启应用后配置的代理丢失，不保存。 ![image](https://private-user-images.githubusercontent.com/14037141/358959473-2229698b-1348-4f9f-9653-1e79105fade9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNzI0NDksIm5iZiI6MTcyNDE3MjE0OSwicGF0aCI6Ii8xNDAzNzE0MS8zNTg5NTk0NzMtMjIyOTY5OGItMTM0OC00ZjlmLTk2NTMtMWU3OTEwNWZhZGU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDE2NDIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNDdmZjc1MTQ2ZDgxN2VkY2JiYzY0YmZhNzk4NTVjYWM2NmRlZDUyMDgzNmZmZjAzMjBkMGU3Y2EwYzUzNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QkS13vtLqplyQn2y-vcvVY7NgJT0MQ6k-v3KrwdpeZ0)

我也遇到了这个问题。保存后，大退，冷启再进来，配置又没了

**Comment by lswang6** [comment]
是的, AMD intel芯片的mac的确会这样.不知道能不能修了.
<img width="989" alt="image" src="https://github.com/user-attachments/assets/1c2922cb-b6fa-457d-a4b3-81bb9c230751">
