### ISSUE TITLE
clash订阅不能直接通过URL导入

### ISSUE THREAD

**Issue by shiayall** [chen08209/FlClash#265]
在cfa可以使用的订阅链接导入失败![Screenshot_2024-08-20-05-08-26-50_ed7cc6eecf382e65e95dbc137f8c2558.jpg](https://github.com/user-attachments/assets/1964c230-d466-4809-a8d7-644b7eebb059)

**Comment by tangwenlongNO1** [comment]
我也有这个问题，帮顶
