### ISSUE TITLE
强烈反对默认就自动开启管理员模式。让用户有自主选择用不用管理员模式开启的自主权。主界面建议加一个纯代理开关，让用户有自主开关系统代理的选择。另外tun模式的开启就用自动开启管理员模式，。还有右下角右键不灵。初打开应用时点不开来

### ISSUE THREAD

**Issue by fyhzc** [chen08209/FlClash#272]

**Comment by fyhzc** [comment]
不要默认就用“管理员模式”开启软件
刚打开软件点任务栏 右下角的图标点键没反应。弹不出右键快捷键

**Comment by fyhzc** [comment]
软件打开不要有任何代理配置的启用。加一个纯代理开关、让用户选中一个配置，再点纯开启代理。
在纯代理模式下
浏览器装个smartproxy扩展就能代理上网。
idm下载软件中设置下代理就能用代理下载外网东东

**Comment by fyhzc** [comment]
其实v0.8.53就很不错，就是主界面少了一个纯代理开关。
而0.8.53版打开软件就是纯代理开启方式

**Comment by chen08209** [comment]
最新版本将不在支持默认管理员模式启动

**Comment by refined-fish** [comment]
> 最新版本将不在支持默认管理员模式启动

是否能将此功能做成开关，作为一个经常使用tun模式的人来说，目前没有服务模式（或者新增tun的服务模式），必须每次都手动右键管理员运行有点麻烦Thanks♪(･ω･)ﾉ
