### ISSUE TITLE
有本地配置存在時選擇全部更新時報錯

### ISSUE THREAD

**Issue by LoreHan64** [chen08209/FlClash#274]
版本：FlClash for Android arm64-v8a 0.8.54（64ad55b）

預期：點按全部更新，遠程配置文件正常更新，無報錯；

實際：點按全部更新，遠程配置文件正常更新，本地配置文件在遠程配置更新完成後報錯（如圖）
![Screenshot_20240822_224430](https://github.com/user-attachments/assets/ffaceb54-11ff-49f9-8567-e955fb97941a)

可能是由於點按全部更新時進行檢測本地配置文件的遠程更新連結導致的失敗（由`No host specified in URI`猜測）

**Comment by chen08209** [comment]
新版本已修复
