### ISSUE TITLE
希望支持从剪贴板一键导入V2Ray节点

### ISSUE THREAD

**Issue by LegendEast** [chen08209/FlClash#275]

**Comment by catxian** [comment]
内核都不一样，clash系没见哪个支持你说这个功能的，单链接就别想了，订阅还差不多

**Comment by Elysia-HerrscherOfHuman** [comment]
> 内核都不一样，clash系没见哪个支持你说这个功能的，单链接就别想了，订阅还差不多

可以转换，比如 [subconverter](https://github.com/tindy2013/subconverter)

![图片](https://github.com/user-attachments/assets/f861a11d-6dbe-470a-9ab4-09ef7b4e3fd9)
