### ISSUE TITLE
云备份报这个

### ISSUE THREAD

**Issue by boy86001** [chen08209/FlClash#280]
![Screenshot_2024-08-23-17-39-59-981_com.follow.clash.jpg](https://github.com/user-attachments/assets/275f2dc6-106c-4325-904a-c6e86550ff84)

![Screenshot_2024-08-23-17-39-54-776_com.follow.clash.jpg](https://github.com/user-attachments/assets/921865ec-1f89-48d6-bfb8-3fcc6388a510)

**Comment by yolomc** [comment]
同

**Comment by chen08209** [comment]
错误提示没有权限，涉及对应的服务端，无法解决
