### ISSUE TITLE
0.8.56的setup exe在Windows 11 24H2下被defender报毒

### ISSUE THREAD

**Issue by snowflake-autumn** [chen08209/FlClash#291]
如题，大佬，报毒信息如下，希望尽快解决，感谢大佬
![屏幕截图 2024-08-26 231204](https://github.com/user-attachments/assets/cea94bae-795e-40d4-a560-ed13131da125)

**Comment by snowflake-autumn** [comment]
> 这是trojan协议的执行程序

您好大佬，请问这种误报怎么解决呢

**Comment by Harris0310** [comment]
不解决啊，把它解除隔离，恢复文件，就可以安装了
