### ISSUE TITLE
允许应用绕过VPN

### ISSUE THREAD

**Issue by cheneyxx** [chen08209/FlClash#293]
![Screenshot_2024-08-27-08-49-56-679_com.follow.clash.jpg](https://github.com/user-attachments/assets/9c0e69c2-5a93-4dd2-8093-c0450e491ccd)

![Screenshot_2024-08-27-08-49-47-883_com.google.android.gms.jpg](https://github.com/user-attachments/assets/a3a078cb-8d93-49c1-aa67-29ed9505dd20)

默认打开此选项会连不上谷歌FCM

**Comment by zxyist** [comment]
同
