### ISSUE TITLE
【Feature】请添加clash for windows的终端运行

### ISSUE THREAD

**Issue by nankingcigar** [chen08209/FlClash#294]
本人个体户码农，网络环境不定，有时候github docker npmjs 会出现连不上，使用了flclash后，浏览器可以打开，但cmd或者powershell的流量不会走flclash，自己网上搜了也没搞定，如果能像clash for windows一样可以选个终端运行，内部设置好了，这样更方便
请添加clash for windows的终端运行
![image](https://github.com/user-attachments/assets/0d4ccc39-af91-4220-a400-476d845e23de)

**Comment by hpcll** [comment]
确实 非常需要
