### ISSUE TITLE
1.软件退出后不自动关闭系统代理设置按钮导致无法上网2.软件退出后任务栏图标不消失问题3.希望软件加入UWP回环功能

### ISSUE THREAD

**Issue by Solblom** [chen08209/FlClash#300]
![1](https://github.com/user-attachments/assets/23619a40-2251-4ac7-ab2b-0d0f19dfbea2)
![2](https://github.com/user-attachments/assets/7c50eaca-e534-43d9-855c-4f635f0a121c)

**Comment by Tpfdd** [comment]
一样，退出后上不了网，这bug太离谱

**Comment by Tpfdd** [comment]
一样，退出后上不了网，这bug太离谱，希望软件加入UWP回环功能

**Comment by chen08209** [comment]
问题2无法复现，1，3最新版均以解决或支持
