### ISSUE TITLE
关于同一个链接导入clash meta和flclash却出现不同情况的问题

### ISSUE THREAD

**Issue by LiMeng356** [chen08209/FlClash#303]
开发者你好，我用同一个链接进行订阅转换之后，导入clash meta的新加坡1节点打开谷歌商店下载是有速度的，但导入flclash之后用新加坡1节点打开谷歌商店下载却没速度，请问这种情况是要在flclash内设置什么东西么

**Comment by odd256** [comment]
你好，我也遇到了同样的问题，使用flclash时可以正常访问谷歌商店，但下载速度始终为0，且切换代理模式为全局或规则都无效

**Comment by yuanbin-dev** [comment]
分析日志，是内置的geoip.dat有问题，services.googleapis.cn不能走geositte cn。
用其他软件使用Loyalsoldier/v2ray-rules-dat规则没问题
