### ISSUE TITLE
功能请求【外部资源添加更详细的信息】

### ISSUE THREAD

**Issue by Aladdinsane3** [chen08209/FlClash#305]
会考虑在移动端的外部资源添加更详细的信息吗？比如proxy providers的到期时间和流量使用情况

**Comment by zyjmaki** [comment]
可以专门给一个proxy-groups用于显示这些信息，比如：

- name:自定义
  type: select
  filter: "剩余|套餐|时间"
  use:
    - 你proxy-providers的name
