### ISSUE TITLE
安卓手机版一直无法添加跳过证书验证的Clash订阅链接

### ISSUE THREAD

**Issue by zscontinent** [chen08209/FlClash#309]
安卓手机版一直无法添加跳过证书验证的Clash订阅链接
![photo_2024-08-29_15-12-39](https://github.com/user-attachments/assets/04732bde-8b1d-4b83-99dd-91c7a4cdc797)

**Comment by chen08209** [comment]
这不是证书认证，而是没有拉取到文件
