### ISSUE TITLE
【BUG】tun模式无法重新开启

### ISSUE THREAD

**Issue by xingxin1590** [chen08209/FlClash#313]
tun模式只有第一次开启软件启动才有效，如果关闭tun再重新开启则无效，需要关闭软件重新打开启动
如图是第一次开启，看右下角网络会显示tun成功
![image](https://github.com/user-attachments/assets/3088f285-6bb5-4bd9-b814-7a54980b198b)
如图是第二次开启，则tun会启动失败，需要关闭软件重新打开才能成功开启tun
![image](https://github.com/user-attachments/assets/451b1b47-78bc-4f25-9085-bcffd419482e)

**Comment by chen08209** [comment]
新版本应该已修复
