### ISSUE TITLE
不会自动更新订阅链接

### ISSUE THREAD

**Issue by sekurodesu** [chen08209/FlClash#322]
如题，设置了隔2分钟自动更新订阅，但是实际使用中，过了几十分钟都没更新，切换到订阅列表栏显示上一次更新订阅是几十分钟前，希望修复此BUG

**Comment by sekurodesu** [comment]
似乎是偶发性的问题，先关闭吧

**Comment by mai19950** [comment]
> 似乎是偶发性的问题，先关闭吧

不是偶发问题，根本就是不会更新的，就算是重启软件，他也不更新，必须是手动点击更新
