### ISSUE TITLE
PC端软件无法自动更新订阅链接

### ISSUE THREAD

**Issue by sekurodesu** [chen08209/FlClash#328]
如题所述，是偶发性问题，有时候会自动更新订阅，有时候一直不自动更新订阅，以截图为例，我设置了2分钟更新一次订阅，实际上过了好久都一直没更新。
![微信图片_20240903091606](https://github.com/user-attachments/assets/bb473b9d-5e1b-4cc6-82de-fb97e0ea64c5)

**Comment by chen08209** [comment]
自动更新，有且只在每次打开软件时判断是否触发
