### ISSUE TITLE
希望Android版新增一个仅代理模式实现与ADGuard共存

### ISSUE THREAD

**Issue by thouser8** [chen08209/FlClash#330]
参考https://iblog.ren/posts/52/
该功能在cmfa中为关闭自动路由系统流量，我在本项目中没有找到类似的功能

**Comment by chen08209** [comment]
最新版，覆写vpn中关闭vpn即可

**Comment by pyy2022** [comment]
请问你现在解决了吗，我虽然root了，但是也无法共存，adguard不工作，没法去广告。

**Comment by PoseidonWake** [comment]
> 请问你现在解决了吗，我虽然root了，但是也无法共存，adguard不工作，没法去广告。

@pyy2022 您好，请问有后续吗？我也是root的设备，之前用cmfa共存很简单，cmfa不做改变，adg的路由模式选自动代理就行。现在这样做adguard工作不正常，只过滤一些app，最重要的chrome等没法过滤

**Comment by pyy2022** [comment]
> > 请问你现在解决了吗，我虽然root了，但是也无法共存，adguard不工作，没法去广告。
> 
> [@pyy2022](https://github.com/pyy2022) 您好，请问有后续吗？我也是root的设备，之前用cmfa共存很简单，cmfa不做改变，adg的路由模式选自动代理就行。现在这样做adguard工作不正常，只过滤一些app，最重要的chrome等没法过滤

无，只能继续用cmfa了。另外，不去广告了，懒得折腾，直接GKD跳过
