### ISSUE TITLE
无法打开软件

### ISSUE THREAD

**Issue by Mgrsc** [chen08209/FlClash#335]
双击运行软件后不显示界面，但是确实在运行，右键点击显示也没用反应，ctrl+tag 显示该程序页面空白
![image](https://github.com/user-attachments/assets/8008acd6-8a4a-46ea-836e-ab70ac3ea172)
![image](https://github.com/user-attachments/assets/15d18a55-1704-463c-a76a-6d3ed4380e1c)
![image](https://github.com/user-attachments/assets/b9398e3a-0db0-44c9-a75b-ecc630f10d3d)

版本	Windows 11 专业工作站版
版本号	23H2
安装日期	‎2024/‎4/‎23
操作系统版本	22631.4037
体验	Windows Feature Experience Pack 1000.22700.1027.0

**Comment by ChenGenwen** [comment]
我也是这样，请问如何解决的？

**Comment by Mgrsc** [comment]
> 我也是这样，请问如何解决的？

换软件
