### ISSUE TITLE
自己建立的节点

### ISSUE THREAD

**Issue by Cminors** [chen08209/FlClash#337]
自己建立的节点怎么转换成订阅地址导入啊，用了很多方法都不行

**Comment by PingZi-Wing** [comment]
第三方订阅转换器，然后proxy-provider引用即可。目前我是借助iOS上的sub-store来转换的，自己的配置里面加个本地proxies，就可以下载转换来的gist链接

**Comment by NormanMises** [comment]
新发现https://github.com/mihomo-party-org/mihomo-party有substore功能
