### ISSUE TITLE
关于内存占用的困惑

### ISSUE THREAD

**Issue by toyo2333** [chen08209/FlClash#338]
windows系统，我之前使用 clash-nyanpasu 1.5版本（内核是 meta 1.18.7） ，看后台进程内存占用，任务管理器是16MB（mihomo）+24MB（clash-nyanpasu），用https://metacubexd.pages.dev/#/overview 看也是差不多44MB左右。（小巧好用，但缺点是tun方面有点问题）

然后我也试过 clash-nyanpasu 的最新版 1.6 内存占用也大概是70MB 左右。

然后我退出去，换成FlClash 0.8.57   只看后台进程内存占用，任务管理器里是220MB（只有FIClash,没有找到mihomo），网页面板https://metacubexd.pages.dev/#/overview 里是286MB左右 

上面2个对比用的配置文件内容相同，都只看后台进程（进程名字不同一个是mihoyo）的内存占用

同一台机器，前后脚测试。怎么会差别这么大？FlClash占用这么大内存是正常状态还是说还有优化的空间。

FlClash挺喜欢的，希望资源占用和性能的表现方面 也能和UI一样 做到简约，清爽，极致~

**Comment by KKFantasy** [comment]
看了下我这任务管理器的占用只有60mb，不知道为什么差别这么大

**Comment by chen08209** [comment]
事实上是你测试的问题，以clash verge rev为例,总共包含三个进程，分别包含webview2，clash verge，verge-mihomo三个进程，在我的电脑上同配置下，内存要比FlClash 高了超过50m
nyanpasu和clash verge rev基本同方案，不做更多讨论
