### ISSUE TITLE
FlClash v0.8.55 至 v0.8.57 Android 无法保存配置

### ISSUE THREAD

**Issue by ericclose** [chen08209/FlClash#346]
复现方法：
1. 全新安装 FlClash
2. 更改 FlClash 为暗色模式/添加配置
3. 从多任务里清除后台
4. 再次打开 app，发现恢复成初始配置

**Comment by Gluneklairo** [comment]
补充：无法保存配置的问题存在于任何设置，例如规则全局直连模式按钮、设置里任何的按钮（包括排除的应用）、订阅的更新、节点与配置的选择，这个问题不知如何抓取log

**Comment by Gluneklairo** [comment]
> 复现方法：
> 
> 1. 全新安装 FlClash
> 2. 更改 FlClash 为暗色模式/添加配置
> 3. 从多任务里清除后台
> 4. 再次打开 app，发现恢复成初始配置

试试打开从“最近任务中隐藏”，然后不要从后台划卡，为在主页返回，你试试这样还会不会丢配置，貌似这样操作内核不会重载，可能是机制问题

**Comment by ericclose** [comment]
> > 复现方法：
> > 
> > 1. 全新安装 FlClash
> > 2. 更改 FlClash 为暗色模式/添加配置
> > 3. 从多任务里清除后台
> > 4. 再次打开 app，发现恢复成初始配置
> 
> 试试打开从“最近任务中隐藏”，然后不要从后台划卡，为在主页返回，你试试这样还会不会丢配置，貌似这样操作内核不会重载，可能是机制问题

已经尝试出一个方法可以保存了，就是一开始修改任何配置后，不要直接从多任务划掉卡片，需要一路返回到桌面，这个时候再划掉就能保存配置

**Comment by eric-gitta-moore** [comment]
macOS版本+1
