### ISSUE TITLE
请问下，在构件  dart .\setup.dart android 中报错误 目录名称无效，这少了什么了吗？

### ISSUE THREAD

**Issue by gzalrj** [chen08209/FlClash#348]
E:\webroot\android\FlClash\FlClash-main>dart .\setup.dart android
run build libclash
run build libclash
run build libclash
run clean distributor
Unhandled exception:
ProcessException: 目录名称无效。

  Command: cmd.exe /c flutter clean
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:402:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      Build.exec (file:///E:/webroot/android/FlClash/FlClash-main/setup.dart:144:35)
#3      Build.getDistributor (file:///E:/webroot/android/FlClash/FlClash-main/setup.dart:221:11)
#4      BuildCommand._buildDistributor (file:///E:/webroot/android/FlClash/FlClash-main/setup.dart:334:17)
#5      BuildCommand.run (file:///E:/webroot/android/FlClash/FlClash-main/setup.dart:382:9)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>

**Comment by chen08209** [comment]
文档没有同步更新，应该还需要加上对应架构，例如dart .\setup.dart android --arch arm64
