### ISSUE TITLE
[Feature Request] 使用系统服务启动虚拟网卡

### ISSUE THREAD

**Issue by xkww3n** [chen08209/FlClash#350]
现在的版本去掉了以管理员身份自动启动的功能，但如果以普通身份启动，虚拟网卡将无法启动。

我不理解 #272 的作者提出这么激进的提案却又不给出任何理由的意义何在，但目前去除以管理员身份启动显然影响了正常使用。若不打算恢复此功能，则应当像其他同类软件一样，使用系统服务的方式实现“软件本体使用普通身份运行，而依然能够正常启动虚拟网卡”

**Comment by llanc** [comment]
附议，当前几个版本普通用户启动后虚拟网卡无法创建

**Comment by alyx404** [comment]
附议，纯TUN用户需要系统服务来维持开机自启的功能……

**Comment by chen08209** [comment]
目前更推荐用户手动设置应用以管理员模式启动
