### ISSUE TITLE
Releases 0.8.59-windows-amd64 打开之后白屏

### ISSUE THREAD

**Issue by zhaoyangpp** [chen08209/FlClash#354]
![image](https://github.com/user-attachments/assets/ab07ebb5-8e0a-40f6-a106-61776bd24084)

**Comment by AmLicor** [comment]
![image](https://github.com/user-attachments/assets/81034ae7-b81f-4281-ac0f-704664651097)
全屏的效果

**Comment by mrshenyc** [comment]
同样的情况，想知道如何解决
