### ISSUE TITLE
希望webdav备份增加多版本备份功能

### ISSUE THREAD

**Issue by qingyu910** [chen08209/FlClash#360]
如下图所示，希望能增加配置版本控制功能
![image](https://github.com/user-attachments/assets/0dcd8558-d90e-43e6-87a0-3e2b0d3ee636)
![image](https://github.com/user-attachments/assets/7f421716-2541-4b46-9e2b-c3d8d027ed30)

**Comment by chen08209** [comment]
目前可以通过修改备份中的备份文件名实现
