### ISSUE TITLE
能否在主界面仪表盘一目了然显示“订阅节点”信息

### ISSUE THREAD

**Issue by motorar** [chen08209/FlClash#362]
仪表盘太多空间处于浪费状态，而平时要查看是使用了哪个节点，还要多点击几次，比较麻烦。
黄颜色区域是我假设的一种安排，希望参考。
![2024-09-12 12 56 18](https://github.com/user-attachments/assets/0e20d64a-42b6-4c63-a949-e58b751c3024)

**Comment by chen08209** [comment]
clash无法获取当前使用节点
