### ISSUE TITLE
求功能说明

### ISSUE THREAD

**Issue by 999man** [chen08209/FlClash#366]
新手小白一个，不知道怎么高级设置软件，有没有说明文档或软件功能介绍？最好详细点。
比如：虚拟网卡啥意思？系统代理啥意思？系统代理+出站模式会怎样？
还请大神们赐教

**Comment by 999man** [comment]
规则在哪设置？软件以内置规则？

**Comment by yonee77** [comment]
没有内置规则，只有内置geoip，规则要自己弄

**Comment by 999man** [comment]
自己怎么设置规则？
