### ISSUE TITLE
win10黑屏，但点击右上角可以最小化，最大化，关闭窗口

### ISSUE THREAD

**Issue by GordonYoungCao** [chen08209/FlClash#371]
如下图所示，全黑，是需要下载qt吗？还是缺少什么软件造成的
![0rjQp4J4X3](https://github.com/user-attachments/assets/5abffd57-0706-4f19-b565-0f727287131d)

**Comment by lunker2019** [comment]
一样，只要是60版本之上的，我都试过了，win10 22h2就是白屏
