### ISSUE TITLE
大佬，mac版，开了TUN模式，ARC浏览器也无法同步书签

### ISSUE THREAD

**Issue by Ch1ha0** [chen08209/FlClash#373]
请问这个要如何设置呢？
macos有两个版本，我下的是第二个，第一个打不开

**Comment by mibesr** [comment]
mac下的tun模式目前不能用

**Comment by Matrixmax** [comment]
sudo chown root:admin /Applications/FlClash.app
sudo chmod +sx /Applications/FlClash.app
这样就可以了，亲测可行
