### ISSUE TITLE
0.8.59，win11系统，FIClash的界面会卡死

### ISSUE THREAD

**Issue by projectttony** [chen08209/FlClash#374]
复现步骤：
1. 正常加载启动，外网状态通畅
2. 配置-切换另一个配置。此时出现长时间切换不成功
3. 仪表盘-点击”暂停“按钮，FIClash卡死

好像只要成功连上一次外网，然后直接切换配置or点击暂停再切换配置，按照步骤操作，都会导致FIClash界面卡死，最后只能通过任务管理器强行结束进程。

**Comment by chen08209** [comment]
启动，暂停，和更改配置都加了互斥锁，同样的操作我这里均无法复现，推荐另一个配置是否有问题

**Comment by projectttony** [comment]
是我的系统不知道哪里被修改了，重装系统，问题解决了。
