### ISSUE TITLE
移动端和windows都无法恢复备份

### ISSUE THREAD

**Issue by sche11** [chen08209/FlClash#38]
下载的压缩包便携版本，使用alist作为webdav，上传成功
![VeryCapture_20240614022327](https://github.com/chen08209/FlClash/assets/37439980/96d0ca33-705b-4caa-9d80-db3b09d44cb1)
但是在使用恢复操作时，显示以下错误，恢复备份失败。
DioException [bad response]: null
Error: Forbidden
![VeryCapture_20240614022024](https://github.com/chen08209/FlClash/assets/37439980/e7bcbc16-423b-4be9-a4f4-397044f39405)

**Comment by armful5862** [comment]
一样，在已有备份的情况下再次备份会失败，只能去手动删除之后再次备份
