### ISSUE TITLE
打开代理可以默认选择延迟最低的节点

### ISSUE THREAD

**Issue by nief12** [chen08209/FlClash#383]
有的订阅不太好，不是所有节点可用或者延迟低，如果可以设置成自动选择延迟低的就不用发现卡还得重新换节点了

**Comment by sakura-xh** [comment]
找个有自动选择的规则组转换一下不就行了

**Comment by nief12** [comment]
> 找个有自动选择的规则组转换一下不就行了

我的自动选择似乎并不会选择延迟最低的，请问有什么特殊的设置吗

**Comment by sakura-xh** [comment]
> > 找个有自动选择的规则组转换一下不就行了
> 
> 我的自动选择似乎并不会选择延迟最低的，请问有什么特殊的设置吗

没有啊，就是url-test类型的策略组，会自动选择延迟最低的，meta内核的文档里是这么写的

**Comment by nief12** [comment]
> > > 找个有自动选择的规则组转换一下不就行了
> > 
> > 我的自动选择似乎并不会选择延迟最低的，请问有什么特殊的设置吗
> 
> 没有啊，就是url-test类型的策略组，会自动选择延迟最低的，meta内核的文档里是这么写的

这样啊，那我研究研究，感谢
