### ISSUE TITLE
load GeoSite data error, failed to decode geodata file: GeoSite.dat, base error: list chinaclassical not found in GeoSite.dat

### ISSUE THREAD

**Issue by piwawa** [chen08209/FlClash#387]
刚刚下载的最新版，打开就报错，且无法使用任何节点 ！

![image](https://github.com/user-attachments/assets/bc3018b5-5c5b-42fd-b1a2-441b77d943c1)

![image](https://github.com/user-attachments/assets/11443aed-9b83-4023-8b0d-9eabe83c61a6)

![image](https://github.com/user-attachments/assets/25e0c04a-df27-4a22-a889-7e988c325762)

**Comment by gemnioo** [comment]
same decode error in openclash mihomo kernel 

https://github.com/vernesong/OpenClash/issues/4033

**Comment by flyingbug2** [comment]
我也是这样，应该是mihomo的问题，用metaX cube也有这个提示。
