### ISSUE TITLE
最新版V0.8.60的仪表盘中“网络检测   只要一启动翻墙联网，就会显示  检测失败  timeout

### ISSUE THREAD

**Issue by fyhzc** [chen08209/FlClash#389]

**Comment by fyhzc** [comment]
![屏幕截图 2024-09-17 235409](https://github.com/user-attachments/assets/c40a54ad-2fd4-49b9-9aa5-2d5ee08ff0d5)

**Comment by likaifenkeng** [comment]
0.8.59在安卓就有这个问题。不仅是检测失败，是网络无法使用。

**Comment by lunker2019** [comment]
0.8.60 win10 can't run

**Comment by lunker2019** [comment]
0.8.60 win10没有办法打开，打开是一片空白

**Comment by chen08209** [comment]
本质上这里的ip检测就是再网络状态发生变动后请求对应网址，如果出现timeout，可以尝试关闭DNS覆写，如果DNS覆写未开启，可以尝试优化配置

**Comment by mrshenyc** [comment]
> 0.8.60 win10打不开，打开的是一片空白

同样的情况，请问你解决了吗

**Comment by lunker2019** [comment]
> > 0.8.60 win10打不开，打开的是一片空白
> 
> 同样的情况，请问你解决了吗

没有，60版本之上的全部都是这样，现在只有用59版本才是好的
