### ISSUE TITLE
桌面版本出现无法进入主界面

### ISSUE THREAD

**Issue by ft3727754** [chen08209/FlClash#392]
![微信图片_20240918163531](https://github.com/user-attachments/assets/1c230629-7f93-4121-b53c-7a905bc8288a)
桌面版本安装后，无法显示主对话框，显示如图，卸载重装无效

**Comment by cc458729102** [comment]
同 无法进入

macos 安装新版本 后

![image](https://github.com/user-attachments/assets/bb713dd3-824d-4c0a-8906-d6cd991440cf)

**Comment by dollar-cat** [comment]
终端执行 cd /Applications/flclash.app/Contents/MacOS/   并 ./flclash.app  将运行输出 截图发上来

**Comment by mrshenyc** [comment]
> 终端执行 cd /Applications/flclash.app/Contents/MacOS/ 并 ./flclash.app 将运行输出截图发上来

你好👋，请问在Windows上的解决方法，万分感谢

**Comment by gssdromen** [comment]
> ./flclash.app

[IMPORTANT:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalSkia.mm(66)] Using the Skia rendering backend (Metal).
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libclash.dylib': dlopen(libclash.dylib, 0x0001): tried: 'libclash.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibclash.dylib' (no such file), '/Applications/FlClash.app/Contents/Frameworks/FlutterMacOS.framework/Versions/A/./libclash.dylib' (no such file), '/usr/local/lib/./libclash.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/./libclash.dylib' (no such file), '/Applications/FlClash.app/Contents/Frameworks/FlutterMacOS.framework/Versions/A/../../../libclash.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/usr/lib/swift/libclash.dylib' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/libclash.dylib' (no such file), '/Applications/FlClash.app/Contents/Frameworks/libclash.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/Applications/FlClash.app/Contents/MacOS/Frameworks/libclash.dylib' (no such file), '/Applications/Xcode_15.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libclash.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode_15.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libclash.dylib' (no such file), '/usr/lib/libclash.dylib' (no such file, not in dyld cache), 'libclash.dylib' (no such file)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22)
#2      ClashCore._getClashLib (package:fl_clash/clash/core.dart:25)
#3      new ClashCore._internal (package:fl_clash/clash/core.dart:34)
#4      new ClashCore (package:fl_clash/clash/core.dart:42)
#5      clashCore (package:fl_clash/clash/core.dart:386)
#6      main (package:fl_clash/main.dart)
#7      _runMain.<anonymous closure> (dart:ui/hooks.dart:301)
#8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
#9      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)

**Comment by gssdromen** [comment]
看了眼堆棧難道是arm和x86下錯了？

**Comment by gssdromen** [comment]
试了下0.8.62版本，arm64可以正常打开

**Comment by ft3727754** [comment]
x86还是打不开

**Comment by sirius422** [comment]
v0.8.62 问题依然存在，在Windows 11 Retail上第一次打开的时候，窗口是正常显示的。但是在关闭窗口后，就无法再次打开了，console上没有任何报错。

没找到log在哪里，所以我也没法提供更详细的信息。

**Comment by mathmost** [comment]
0.8.62win也不行
