### ISSUE TITLE
【BUG】最新版60，华为鸿蒙系统中下拉快捷开关会失灵

### ISSUE THREAD

**Issue by xingxin1590** [chen08209/FlClash#394]
重启手机后的第一次点击是有效的，但是第一次过后就会失效，已经重启四次均是如此，实测退回59版本有效

**Comment by ALTdeveloper** [comment]
机型Mate40，系统版本鸿蒙4.2.0中同样存在此bug

**Comment by xingxin1590** [comment]
> 机型Mate40，系统版本鸿蒙4.2.0中同样存在此bug

新版问题，退回59后有效

**Comment by xingxin1590** [comment]
> 机型Mate40，系统版本鸿蒙4.2.0中同样存在此bug

最新版61解决了问题
