### ISSUE TITLE
需要完善国际化语言支持

### ISSUE THREAD

**Issue by xianhongtao** [chen08209/FlClash#399]
我在与管理员讨论为FlClash添加[alternativeto.net界面](https://alternativeto.net/software/flclash/about/)时，管理员提到该软件目前没有英文版的官方网站，且在GitHub上也缺乏英文版的截图，因此认为该软件不支持英文。
对此，我认为FlClash需要更多开发者的支持，因此吸引来自其他国家的开发者参与是非常重要的。
请作者提供更完善的国际语言支持。

**Comment by chen08209** [comment]
暂时不考虑更多语言支持

**Comment by xianhongtao** [comment]
你这软件甚至没有实现100%英语，你要是只想提供中文语言支持，那你还用英语写release干啥，为啥不直接用中文？
