### ISSUE TITLE
希望添加合并（merge）功能

### ISSUE THREAD

**Issue by Miyo333** [chen08209/FlClash#40]
合并（merge）是一个非常实用的功能，在电脑端的主流客户端基本都有，但是从来没有在手机端上出现过，导致在手机上想要更改配置变得相当麻烦。要么手动修改配置文件，一旦更新就要重新修改，要么就要自己建立一个转换节点修改订阅，过于麻烦且浪费资源。
有了这个功能就可以大大提高使用体验。

**Comment by efaun** [comment]
臣附议

**Comment by yifai** [comment]
用proxy-providers，自定义配置，随便你怎么写策略、规则
