### ISSUE TITLE
win11任务栏图标丢失

### ISSUE THREAD

**Issue by HHXXYY123** [chen08209/FlClash#409]
随机出现任务栏图标丢失的问题，暂不知其原因，任务管理器有程序，结束任务后重新打开会出现任务栏图标，可以通过快捷键唤出两个月内的版本到0.8.61都有这个问题

**Comment by YuHuanTin** [comment]
win10也存在，随机消失

**Comment by caolib** [comment]
0.8.62没有修复，还以为退出了，实际上只是图标不见了

**Comment by YuHuanTin** [comment]
0.8.63没有修复，重启explorer就消失的现象依旧存在
