### ISSUE TITLE
flclash 暂停后无法上网

### ISSUE THREAD

**Issue by liudao01** [chen08209/FlClash#410]
平台: mac  
版本 : 0.8.61
现象: 现在只要把Flclash关闭 就无法上网了, 即时把FlClash暂停, 包括系统代理, 虚拟网卡关闭都不行, 包括暂停,退出, 停止系统那个代理,停止虚拟网卡都试过 不行

**Comment by boyiz** [comment]
**我也有相同的问题**

**Comment by liudao01** [comment]
> **我也有相同的问题**

我已经放弃这个了 换其他的用
