### ISSUE TITLE
某一类的订阅链接无法导入

### ISSUE THREAD

**Issue by imsoosa** [chen08209/FlClash#412]
有一类的订阅链接无法导入，会提示如下图所示错误
<img src="https://github.com/user-attachments/assets/f24cf7d6-6734-4c0c-b7d9-02a1d897bbc2" width=300>

测试订阅链接：
https://flynb.site/sub?token=F9F9zZcllpdyN5TluF9F9zZF9F9zZ11EEfx0g&tag=clash

**这一类订阅链接的共同点是：在浏览器访问时直接就会弹出yaml文件下载**

<img src="https://github.com/user-attachments/assets/26f1127d-7e0e-42a7-b897-077513297500" width=400>

（而大部分订阅地址浏览器访问的时候会直接在网页呈现配置文件内容，如下图）
<img src="https://github.com/user-attachments/assets/167fbced-5117-489f-a828-16921deb7453" width=400>

**Comment by chen08209** [comment]
提示信息≈下载文件为空
可通过调整ua或者联系服务提供方提供FlClash的配置分发
