### ISSUE TITLE
url test分组居然选择了默认第一个但是超时的节点

### ISSUE THREAD

**Issue by likaifenkeng** [chen08209/FlClash#418]
不论规则还是全局模式，url test分组居然选择了默认第一个但是超时的节点，所以导致无法联网

手工选节点规则模式可以联网。

安卓。
刚安装的最新app

![IMG_20240928_111722](https://github.com/user-attachments/assets/0213c846-05b7-4ad7-beb7-9bd7cda87bf6)

**Comment by Quackgrass** [comment]
长时间后，会切换到第一个节点，无论是否超时，是否是延迟最小（开启了统一延迟）。此时尝试手动选取节点，但不会切换到选择的节点，重新开关后恢复正常。

基本上注意到已经超过20小时，不确定出现的最小时间节点，但稳定复现。最新的 0.8.67 的Android 和 Windows 都还有这个问题。
