### ISSUE TITLE
[BUG] 安卓端关闭兼容模式后，扫描二维码会闪退

### ISSUE THREAD

**Issue by dongchengjie** [chen08209/FlClash#42]
虽然不理解兼容指的是什么意思，但是关闭后扫描某些订阅的二维码后会直接闪退，再次打开app是黑屏，只能划掉后台再次打开。
且这些订阅在nav上会没有**代理**这个Tab，启用兼容模式后正常使用。

机型: Redmi K70E

**Comment by chen08209** [comment]
非兼容模式目前还在计划中，这个模式下预计未来只会获取节点，目前不推荐打开。
