### ISSUE TITLE
浮窗位置出现偏移

### ISSUE THREAD

**Issue by RUMUJIESHIYIHan** [chen08209/FlClash#420]
在运行后台浮窗位置偏移 在侧边栏将应用关闭再打开也是会出现位置偏移

**Comment by RUMUJIESHIYIHan** [comment]
![Screenshot_2024-09-28-18-50-56-86_ed7cc6eecf382e65e95dbc137f8c2558.jpg](https://github.com/user-attachments/assets/552ff326-bb00-478d-8682-03159f567607)

**Comment by chen08209** [comment]
无法复现
