### ISSUE TITLE
ubuntu 使用报错

### ISSUE THREAD

**Issue by flameleo11** [chen08209/FlClash#423]

**Comment by flameleo11** [comment]
(base) mi@e5-desktop:/drive_d/app/FlClash-0.8.62-linux-amd64$ x FlClash-0.8.62-linux-amd64.deb
(base) mi@e5-desktop:/drive_d/app/FlClash-0.8.62-linux-amd64$ ./FlClash-0.8.62-linux-amd64.deb 
./FlClash-0.8.62-linux-amd64.deb: line 1: syntax error near unexpected token `newline'
./FlClash-0.8.62-linux-amd64.deb: line 1: `!<arch>'
(base) mi@e5-desktop:/drive_d/app/FlClash-0.8.62-linux-amd64$ ll
total 30M
drwxrwxr-x  2 mi mi 4.0K Sep 29 17:31 ./
drwxrwxr-x 24 mi mi 4.0K Sep 29 17:31 ../
-rwxrwxr-x  1 mi mi  30M Sep 29 17:30 FlClash-0.8.62-linux-amd64.deb*
(base) mi@e5-desktop:/drive_d/app/FlClash-0.8.62-linux-amd64$ ./FlClash-0.8.62-linux-amd64.deb 
./FlClash-0.8.62-linux-amd64.deb: line 1: syntax error near unexpected token `newline'
./FlClash-0.8.62-linux-amd64.deb: line 1: `!<arch>'
(base) mi@e5-desktop:/drive_d/app/FlClash-0.8.62-linux-amd64$ ll
total 37M
drwxrwxr-x  2 mi mi 4.0K Sep 29 17:32 ./
drwxrwxr-x 24 mi mi 4.0K Sep 29 17:31 ../
-rw-rw-r--  1 mi mi  37M Sep 29 17:32 FlClash-0.8.62-linux-amd64.AppImage
(base) mi@e5-desktop:/drive_d/app/FlClash-0.8.62-linux-amd64$ x FlClash-0.8.62-linux-amd64.AppImage
(base) mi@e5-desktop:/drive_d/app/FlClash-0.8.62-linux-amd64$ ./FlClash-0.8.62-linux-amd64.AppImage 
./FlClash: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./FlClash)
./FlClash: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by usr/lib/libstdc++.so.6)
./FlClash: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by usr/lib/libstdc++.so.6)
./FlClash: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by usr/lib/libstdc++.so.6)
./FlClash: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.35' not found (required by usr/lib/libgcc_s.so.1)
./FlClash: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by usr/lib/libgcc_s.so.1)

**Comment by flameleo11** [comment]
![image](https://github.com/user-attachments/assets/bbb4ff22-a8d7-44fc-ae42-ef5abe3611e8)

**Comment by lijian-cnsd** [comment]
作者环境中的glibc版本太高了，只能自己手动编译或者看作者是否愿意降版本

**Comment by lijian-cnsd** [comment]
或者作者编译时将cgo关闭（CGO_ENABLED=0），是否就可以避免glibc版本的问题

**Comment by qizeng19** [comment]
解决了吗？ 还是爆同样地错误

**Comment by wentywenty** [comment]
我也是这个错，ubuntu20.04

![Image](https://github.com/user-attachments/assets/a8d264b0-bb00-4722-9fe2-f2096c9934ad)
