### ISSUE TITLE
fl支持自定义分流么？

### ISSUE THREAD

**Issue by David-plz** [chen08209/FlClash#427]
我的一个订阅导入后缺少chatgpt的分流，如果想自己定义chatgpt走美国节点请问应该如何设置？

**Comment by hhhk1** [comment]
你需要在配置文件里面自己修改，然后以文件的形式导入

**Comment by David-plz** [comment]
> 你需要在配置文件里面自己修改，然后以文件的形式导入

格式是什么样的？在配置文件最下方的rules下边：RULE-SET,chatgpt,美国节点。是这样么？

**Comment by marlunzhang** [comment]
> > 你需要在配置文件里面自己修改，然后以文件的形式导入
> 
> 格式是什么样的？在配置文件最下方的rules下边：RULE-SET,chatgpt,美国节点。是这样么？

自行Google clash mihomo的官方wiki，这个不属于flclash的问题

**Comment by colt7676** [comment]
> 你需要在配置文件里面自己修改，然后以文件的形式导入

这样一更新订阅又要重新弄一次，不是优雅的方案。
