### ISSUE TITLE
编辑配置内的自动更新未生效

### ISSUE THREAD

**Issue by xoevdv** [chen08209/FlClash#449]
0.8.63版本的编辑配置内的自动更新未生效，不管是调到1分钟，0分钟，还是60分钟，都不会到了设定时间自动刷新，希望可以修复一下
![Screenshot_2024-10-09-22-55-34-339_com follow clash](https://github.com/user-attachments/assets/6c4614c6-dcc7-4292-b046-c89f301a8099)

**Comment by xoevdv** [comment]
不但不能自动更新，连刷新都不能动态刷新，如果不切换节点，那的刷新时间一直不会变，但即使切换了节点，仍旧不会按照设定时间自动刷新

**Comment by xoevdv** [comment]
安卓端的

**Comment by NormanMises** [comment]
pc也这样 就是bug
