### ISSUE TITLE
能否添加hosts覆写功能？

### ISSUE THREAD

**Issue by kljjh** [chen08209/FlClash#45]
国行安卓的fcm推送需要添加hosts才能正常使用 参见：https://github.com/getsurfboard/surfboard/issues/173
原版cfw和surfboard都有相应功能了 FlClash能否也添加相应功能 或者有没有其他解决方案

**Comment by chen08209** [comment]
现阶段可以通过配置文件添加hosts

![Snipaste_2024-06-15_22-21-33](https://github.com/chen08209/FlClash/assets/66918471/27a3d357-0068-4d39-956d-7879fae9a6b0)

[clash.meta文档](https://wiki.metacubex.one/config/dns/hosts/)

**Comment by kljjh** [comment]
> 现阶段可以通过配置文件添加hosts
> 
> ![Snipaste_2024-06-15_22-21-33](https://private-user-images.githubusercontent.com/66918471/339995971-27a3d357-0068-4d39-956d-7879fae9a6b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NjMwMjUsIm5iZiI6MTcxODQ2MjcyNSwicGF0aCI6Ii82NjkxODQ3MS8zMzk5OTU5NzEtMjdhM2QzNTctMDA2OC00ZDM5LTk1NmQtNzg3OWZhZTlhNmIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDE0NDUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMzFjNDU0MmYyOTA2NWY2MzFkODNkZjI1NDdhMWM4NTA1ZTZlYThhY2RjMzVhMDdmODM1M2UyMDIzYzc2ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ydg0VIiqYbSX4tz_JtZt6LIiaicQrUEwt-HDjsjVH-M)
> 
> [clash.meta文档](https://wiki.metacubex.one/config/dns/hosts/)

感谢 第一次知道subconverter支持clash meta的hosts覆写 已解决
