### ISSUE TITLE
运行代码时出现崩溃

### ISSUE THREAD

**Issue by devchuan** [chen08209/FlClash#458]
通过编译运行后的源代码。无规律性的出现崩溃。编译的dmg安装不回崩溃

日志如下
signal 16 received but handler not on signal stack
mp.gsignal stack [0x14000086000 0x1400008e000], mp.g0 stack [0x16f11c000 0x16f31f000], sp=0x14000055608
fatal error: non-Go code set up signal handler without SA_ONSTACK flag

runtime stack:
runtime.throw({0x141299b9a?, 0x0?})
	/usr/local/go/src/runtime/panic.go:1023 +0x40 fp=0x14000055560 sp=0x14000055530 pc=0x140839d30
runtime.sigNotOnStack(0x10, 0x14000055608, 0x14000082008)
	/usr/local/go/src/runtime/signal_unix.go:1065 +0x118 fp=0x14000055590 sp=0x14000055560 pc=0x140854b18
runtime.adjustSignalStack(0x10, 0x14000082008, 0x14000055638)
	/usr/local/go/src/runtime/signal_unix.go:592 +0x25c fp=0x14000055600 sp=0x14000055590 pc=0x14085397c
runtime.sigtrampgo(0x10, 0x140000557a0, 0x14000055808)
	/usr/local/go/src/runtime/signal_unix.go:480 +0x8c fp=0x14000055680 sp=0x14000055600 pc=0x1408534bc
runtime.sigtrampgo(0x10, 0x140000557a0, 0x14000055808)
	<autogenerated>:1 +0x1c fp=0x140000556b0 sp=0x14000055680 pc=0x14087909c
runtime.sigtramp()

**Comment by TCOTC** [comment]
我这里 APP 也是时不时就崩了要重新打开

**Comment by devchuan** [comment]
[crash.txt](https://github.com/user-attachments/files/17358306/crash.txt)
从控制台拷贝的日志。大概就是这样。搜了下好像是信号量的原因。但查不到信号量的来源和原因。
