### ISSUE TITLE
希望可以调整代理界面的布局

### ISSUE THREAD

**Issue by MisakaOne** [chen08209/FlClash#46]
![Screenshot_2024-06-16-17-38-02-436_com github metacubex clash meta](https://github.com/chen08209/FlClash/assets/108571772/2598149b-c6dc-40e5-9551-8fecb35a6359)
像图上这样

**Comment by chen08209** [comment]
目前不考虑，后续会增加类似cfw这样折叠面板的布局

**Comment by MisakaOne** [comment]
好的 只是感觉目前每个节点占用的位置太大了 不太美观
