### ISSUE TITLE
TV端在加载代理文件时出现PlatformException(invalid_format type, Can'thandle the provided file type., null, null)错误。

### ISSUE THREAD

**Issue by chenosyong** [chen08209/FlClash#480]
![5](https://github.com/user-attachments/assets/1cfe1826-9a86-45d7-97a9-cf0c050aaa2b)
![2](https://github.com/user-attachments/assets/253472e0-6537-4d5a-94ee-948bf364516c)

**Comment by chenosyong** [comment]
建议：在录入订阅地址边上增加一个二维码功能，可以通过手机扫码直接贴入地址信息，然后通过摇控点确定（目前摇控无法点击确定）。

**Comment by refined-fish** [comment]
这个提示是你的配置文件有问题吧

**Comment by gengdata** [comment]
遇见了同样的问题，请问楼主怎么解决的？
