### ISSUE TITLE
V0.8.64，mac端下载后打开黑屏

### ISSUE THREAD

**Issue by burtgit** [chen08209/FlClash#484]
<img width="800" alt="image" src="https://github.com/user-attachments/assets/24df741a-4a1d-4db1-88f6-c26ca3e1e2e1">

**Comment by isr4z6er** [comment]
看是不是下载错平台版本了？

我一开始打开也是黑屏。我是直接点击的MacOs Universal图标下载的，但实际那个是amd64的- -。
<img width="794" alt="image" src="https://github.com/user-attachments/assets/1abb99f2-e606-43d8-8375-166ec9f66279">


重新在Assets里面下载arm64版本的就ok了。
