### ISSUE TITLE
[BUG] 外部控制xd面板手动切换策略组中的节点，在APP-代理的面板中没有同步切换

### ISSUE THREAD

**Issue by hsingyin** [chen08209/FlClash#508]
## 描述:
打开外部控制，使用xd面板手动切换策略组中的节点，实际已经切换生效，但是在APP-代理的面板UI中没有同步切换选中。

#### 1. 新增配置文件相关字段：
```bash
secret: '123456'
external-controller: 127.0.0.1:9090
external-ui: xd
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip" #从 GitHub Pages 分支获取
```
### 实际结果:
策略组中的节点没有同步切换

## 预期结果:
打开外部控制，使用xd面板手动切换策略组中的节点，在APP-代理的面板UI中同步切换选中对应节点。

**Comment by chen08209** [comment]
设计如此，app内对节点选中有单独缓存

**Comment by hsingyin** [comment]
> 设计如此，app内对节点选中有单独缓存

但是实际上在最近请求查看使用的节点已经跟随外部web控制器切换，app UI  没切换，如果有缓存，不应该统一行为吗？

**Comment by refined-fish** [comment]
> https://d.metacubex.one/#/

朋友，想请问一下，为什么Windows这些平台运行的mihomo，无法直接访问127.0.0.1:端口，而是要访`https://d.metacubex.one/#/`呢，运行在openwrt上的就可以直接访问路由器IP+端口

**Comment by hsingyin** [comment]
> > https://d.metacubex.one/#/
> 
> @hsingyin 朋友，想请问一下，为什么Windows这些平台运行的mihomo，无法直接访问127.0.0.1:端口，而是要访`https://d.metacubex.one/#/`呢，运行在openwrt上的就可以直接访问路由器IP+端口

@refined-fish 关于Windows这些平台运行的mihomo我不是很清楚，猜测因为你本地并没有启动一个web前端服务（即外部web控制器），所以无法访问，通过访问别人部署好的前端服务配置后端接口地址来使用，至于openwrt上的例如openClash可能实现了这部分逻辑。

**Comment by refined-fish** [comment]
> > @hsingyin 朋友，想请问一下，为什么Windows这些平台运行的mihomo，无法直接访问127.0.0.1:端口，而是要访`https://d.metacubex.one/#/`呢，运行在openwrt上的就可以直接访问路由器IP+端口
> 
> @refined-fish 关于Windows这些平台运行的mihomo我不是很清楚，猜测因为你本地并没有启动一个web前端服务（即外部web控制器），所以无法访问，通过访问别人部署好的前端服务配置后端接口地址来使用，至于openwrt上的例如openClash可能实现了这部分逻辑。

我检查了一些，似乎是，在运行目录下ui下面的metacubexed是空的，我也在日志中找到了报错
`Error downloading UI: can't download  file: Get "": unsupported protocol scheme ""`
我非常迷惑，因为配置文件中实际上是这样写的
```
secret: "567458567856"  #⭕API面板访问通用密钥，不设置的话，APP无法打开控制面板
external-ui: ./ui  #⭕静态资源的路径
external-ui-name: metacubexd  #⭕外部面板的名字，配合路径合并成特定面板的路径，例如/ui/metacubexd
external-ui-url: "https://ghp.ci/https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"  #⭕外部面板下载地址
```
感觉实际运行的时候，url被清空了发给内核的？
