### ISSUE TITLE
主题预览功能可能存在问题

### ISSUE THREAD

**Issue by Tritium-Ultra** [chen08209/FlClash#51]
如图一所示，主题预览界面是空白的，应该出现的结果是图二的surfboard的截图<br><br>

<br>图一<br>
![Screenshot_2024-06-17-12-26-19-419_com follow clash](https://github.com/chen08209/FlClash/assets/114449593/3d03a779-4dc2-4990-b50f-8ed41c7b1925)

<br>图二<br>
![Screenshot_2024-06-17-12-29-46-856_com getsurfboard](https://github.com/chen08209/FlClash/assets/114449593/dcd37537-b239-4d66-b015-00eca9ec0f5b)

**Comment by chen08209** [comment]
确实一直没写，主观上不是很想cpoy surfboard这部分的内存，认为不是很美观

**Comment by Tritium-Ultra** [comment]
这是来自foxmail自动回复邮件你好，我最近正在忙，无法亲自回复你的邮件，我将在事务处理结束后，尽快给你回复

**Comment by ailongfei** [comment]
电脑适配建议加个滚动条，或者固定宽度，不然没办法选择左右滑动。 @chen08209
