### ISSUE TITLE
功能请求：增加托盘图标不同状态

### ISSUE THREAD

**Issue by n-ine** [chen08209/FlClash#513]
系统：windows 10 amd64
版本：FIClash v0.8.66

个人一般习惯于用快捷键切换系统代理 并且几乎打开就需要用仅代理功能 所以使用了自动运行
ficlash默认只有两种托盘图标 停止代理和开启代理的图标 并没有系统代理的特殊状态

这样会在用浏览器的时候该代理的时候没代理 需要用快捷键测试一次才知道当前代理状态 或者打开主界面UI才知道
希望把仅代理的状态改为原有不代理状态的图标  开启系统代理再用现在的开启代理图标  或者单独增加一个系统代理的图标来区分于仅代理的图标  这样会直观明了一点
感觉这样能帮到不少和我一样惯于用快捷键切换代理的人 如果愿意采纳会万分感谢

**Comment by chen08209** [comment]
目前不会考虑，现有的支持也会逐步移除，因为多个平台获取主题导航栏颜色过于复杂，最后win平台将始终使用彩色图标，mac因为提供了相关api会根据主题调整颜色
