### ISSUE TITLE
[Linux] TUN Interface Start Error After Updating from 0.8.64 to 0.8.65

### ISSUE THREAD

**Issue by jieran233** [chen08209/FlClash#515]
**Description:**

After updating FlClash from version 0.8.64 to 0.8.65, starting the TUN interface results in the following error:

```
Start TUN listening error: configure tun interface: device or resource busy
```

I've confirmed that this issue persists in version 0.8.66 as well.

Update: the issue still exist in 0.8.67.

**Steps to reproduce:**
1. Update FlClash from 0.8.64 to 0.8.65/0.8.66/0.8.67.
2. Attempt to start the TUN interface.

**Expected behavior:**
The TUN interface should start without errors.

**Actual behavior:**
An error occurs, stating that the TUN interface cannot be configured due to "device or resource busy."

**Affected versions:**
- FlClash version: 0.8.65 0.8.66 0.8.67

**Additional information:**
```
System:
  Kernel: 6.12.0-rc5-2-cachyos-rc arch: x86_64 bits: 64 compiler: clang
    v: 18.1.8
  Desktop: GNOME v: 47.1 Distro: EndeavourOS base: Arch Linux
```
- Install method: AUR PKGBUILD (based on .deb binary releases) https://aur.archlinux.org/packages/flclash-bin

Please investigate this issue, as it impacts TUN functionality for multiple versions beyond 0.8.64.

**Comment by codetang-2417** [comment]
Hello! Apologies as my question is a bit off-topic from the main issue here. I’m using FlClash on Arch Linux, and after starting it, I notice it doesn’t start with administrator privileges, so I’m unable to enable TUN mode. Could you kindly guide me on how to enable TUN mode on Arch Linux? Thank you very much!

**Comment by jieran233** [comment]
> Hello! Apologies as my question is a bit off-topic from the main issue here. I’m using FlClash on Arch Linux, and after starting it, I notice it doesn’t start with administrator privileges, so I’m unable to enable TUN mode. Could you kindly guide me on how to enable TUN mode on Arch Linux? Thank you very much!

This is my solution, perhaps not the best-practice (I'm not a professional), but it works well :)

First, create this following `proxy-service.sh` in directory which you used to put user scripts.
- It was normalized by AI
- You should put your password into `SUDO_PASSWORD`. It will re-run itself with sudo when you call the script without root
- The reason of `--synctime` is that I found NTP time synchronization may not work well with TUN, use this parameter can synchronize system time before starting proxy

<details>
  <summary>Show/Hide proxy-service.sh</summary>
  
```shell
#!/bin/bash

#===============================================================================
# Script Name: proxy-service.sh
# Description: Manages a proxy service (FlClash) with root privileges and time sync
#
# Usage: ./proxy-service.sh [--synctime]
#   --synctime: Optional flag to synchronize system time before starting
#
# Dependencies:
#   - sudo
#   - ntpd
#   - ping
#===============================================================================

# Configuration
readonly PROXY_NAME="FlClash"
readonly PROXY_PATH="/usr/share/FlClash/FlClash"
readonly SUDO_PASSWORD="<your_password>"  # WARNING: Storing passwords in scripts is not secure
readonly PING_TEST_HOST="8.8.8.8"
readonly NTP_TIMEOUT=10

#-------------------------------------------------------------------------------
# Function: check_root
# Description: Checks if script is running as root, if not re-runs with sudo
#-------------------------------------------------------------------------------
check_root() {
    if [ "$EUID" -ne 0 ]; then
        echo "$SUDO_PASSWORD" | sudo --stdin su -c "$(realpath "$0") $*"
        exit $?
    fi
}

#-------------------------------------------------------------------------------
# Function: check_process_running
# Description: Checks if the proxy process is already running
# Returns: 0 if not running, 1 if running
#-------------------------------------------------------------------------------
check_process_running() {
    if pgrep -x "$PROXY_NAME" > /dev/null; then
        echo "Error: $PROXY_NAME is already running."
        return 1
    fi
    return 0
}

#-------------------------------------------------------------------------------
# Function: sync_system_time
# Description: Synchronizes system time using NTP if internet is available
#-------------------------------------------------------------------------------
sync_system_time() {
    echo "Attempting to sync system time..."
    
    # Check internet connectivity first
    if ping -c 1 "$PING_TEST_HOST" > /dev/null 2>&1; then
        if timeout "${NTP_TIMEOUT}s" ntpd -qg; then
            echo "Time synchronization successful."
        else
            echo "Warning: Time synchronization failed."
        fi
    else
        echo "Warning: No internet connection available, time sync skipped."
    fi
}

#-------------------------------------------------------------------------------
# Main Script Execution
#-------------------------------------------------------------------------------

# Check for root privileges
check_root "$@"

# Check if proxy is already running
check_process_running || exit 1

# Process command line arguments
for arg in "$@"; do
    case "$arg" in
        --synctime)
            sync_system_time
            ;;
        *)
            # Invalid argument handling could be added here
            ;;
    esac
done

# Start the proxy service
echo "Starting $PROXY_NAME..."
"$PROXY_PATH"
```

</details>

Then, create a `.desktop` file in user-specific XDG Autostart directory (`$XDG_CONFIG_HOME/autostart`)
https://wiki.archlinux.org/title/XDG_Autostart

<details>
  <summary>Show/Hide FlClash.desktop</summary>

```ini
[Desktop Entry]
Type=Application
Name=FlClash
Comment=FlClash startup script
Exec=</path/to/proxy-service.sh> --synctime
StartupNotify=false
Terminal=false
```

</details>

And last, you can override system-wide desktop entries (`/usr/share/applications/`) with user-specific (`~/.local/share/applications`)!
https://wiki.archlinux.org/title/Desktop_entries

```shell
cp /usr/share/applications/FlClash.desktop ~/.local/share/applications
```
Edit `~/.local/share/applications/FlClash.desktop`:

<details>
  <summary>Show/Hide FlClash.desktop</summary>

```ini
[Desktop Entry]
Type=Application
Name=FlClash
GenericName=FlClash
Icon=FlClash
Exec=</path/to/proxy-service.sh>
Categories=Network;
Keywords=FlClash;Clash;ClashMeta;Proxy;
StartupNotify=true
```

</details>

**Comment by codetang-2417** [comment]
Thank you so much for your detailed response! Your guidance was incredibly helpful, and I was able to successfully enable TUN mode on Arch Linux. I really appreciate you taking the time to help me out!
