### ISSUE TITLE
关于安卓控制中心快捷开关异常的问题

### ISSUE THREAD

**Issue by YanBai233** [chen08209/FlClash#520]
## 安卓控制中心快捷开关异常 ##
系统版本：Android15 / OriainOS5
软件版本：FlClash 0.8.66
## 复现 ##
1. 通过下拉“控制中心”中的“应用快捷功能”启动代理；
2. 正常运行10分钟至40分钟；
3. 再次通过“应用快捷功能”关闭代理。
## 问题表现 ##
1. 快捷功能图标变灰，但是状态栏“VPN”标志依旧显示，通知栏显示代理依旧运行（显示“VPN”图标）；
2. 此时代理实际已经异常，无法再代理流量，所有软件均不能正常联网（包括大陆流量）；
3. 无法再通过“长按快捷功能图标”打开FlClash；
4. 通过桌面图标打开FlClash后发现代理依旧在运行，但是IP检测显示“timeout”；
5. 正常关闭代理后，短时间内网络异常无法恢复，需要关闭所有软件重新操作。
## 问题排查 ##
确认将FlClash归入了防杀后台白名单。
确认使用的节点始终正常。

**Comment by Waterman1997** [comment]
补充一个我遇到的安卓通知栏快捷开关的问题
添加快捷开关按钮后，关机重启手机后按钮消失，需重新添加
手机型号 一加8
安卓版本13
Oxygen OS13.1

**Comment by samir2015dzh** [comment]
我也遇到了lz说的问题，点了快捷开关也有弹窗提示正在关闭vpn了，但是实际上没关掉，状态栏上还是显示vpn开着，必须点那个快捷开关，再开关一次才能关掉
手机型号 小米15pro
安卓版本 15
Hyper os 2.0.20.0

**Comment by chen08209** [comment]
最新版已解决
