### ISSUE TITLE
在当前系统中无法正常显示ui

### ISSUE THREAD

**Issue by yin2hao** [chen08209/FlClash#525]
![Image_1730561865241](https://github.com/user-attachments/assets/f457007e-ab05-4a38-8fc7-dddfcd1a7040)
![Image_1730562019994](https://github.com/user-attachments/assets/5173811f-d39d-4d1e-83b1-0dbe4599d5a5)

**Comment by RainmanGH** [comment]
![截屏2024-11-03 11 20 19](https://github.com/user-attachments/assets/003b0eb0-cc58-40b6-b1f8-9cacd21e4112)
Mac 15.0.1系统，也是不显示UI

**Comment by RainmanGH** [comment]
> ![截屏2024-11-03 11 20 19](https://private-user-images.githubusercontent.com/139841242/382529897-003b0eb0-cc58-40b6-b1f8-9cacd21e4112.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NDgwNDMsIm5iZiI6MTczMDk0Nzc0MywicGF0aCI6Ii8xMzk4NDEyNDIvMzgyNTI5ODk3LTAwM2IwZWIwLWNjNTgtNDBiNi1iMWY4LTljYWNkMjFlNDExMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QwMjQ5MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTQ2YmEyMDA2N2UyOGEwZjQ3NDg3YmNhNWYwM2U3NTI5YjRiYTA1NWQzN2EwMDE1ZTU2ZmZjZDZiZTRiZTQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.J4hahtoUWV3nCVRn0mGKiyEuiK2QZthJ41pZ4xT-S90) Mac 15.0.1系统，也是不显示UI

解决了，直接点击下载，不是arm版本的。。从下方列表里找到arm版的，就OK了
