### ISSUE TITLE
在我的win10电脑上，Flclash一直白屏，无法运行，也没有托盘图标

### ISSUE THREAD

**Issue by Holocure** [chen08209/FlClash#531]
在另一台电脑上运行一切正常，出现问题的电脑版本是20H2. 请问大佬有没有头绪，是哪里出现了异常导致这个结果
![image](https://github.com/user-attachments/assets/144b8b18-e81d-41ba-b816-e477c7277718)
谢谢！

**Comment by Holocure** [comment]
再补充一点: 其他flutter应用都比较正常，比如clashverge.

**Comment by shatiaoaige** [comment]
我也有相应的问题。22h2的win10，不知道怎么才能获取运行时的错误log来提交。

**Comment by Holocure** [comment]
我打算学学flutter, 看能否找出问题的根源😅

**Comment by Cokedoge** [comment]
请问是否解决了  我也出现了这个问题
