### ISSUE TITLE
开发IOS端,打造全链路.

### ISSUE THREAD

**Issue by lxtx528** [chen08209/FlClash#534]
大佬,什么时候开发IOS客户端,打造全链路顶级代理工具?

**Comment by blue2018** [comment]
真的，现在就只差ios了，而且ios最缺这类工具~

**Comment by Novimide** [comment]
iOS端的代理软件已经很优秀了,无论是入门的shadowrocket,loon;或者进阶的quantumultx surge.都是很合格的代理软件,且能够添加很多个性化的功能,可能唯一缺点就是收费;
ios由于其封闭的特性,上架的app必须符合苹果的严苛规则,而且收入有抽成;不上架进行自签的话,你也不希望你用的软件七天就保费一次吧
开发者没有必要做这个费事费力还不赚钱的项目

**Comment by blue2018** [comment]
有些事做了并非都为了金钱，有不少开发者就是为了成就感而为

**Comment by RebelliousWhiz** [comment]
开源软件 iOS 版收费不是很正常的事情吗，强烈建议收费上架 iOS

**Comment by KKFantasy** [comment]
iOS不是有stash吗
