### ISSUE TITLE
windows 的tun模式能否上 “服务模式”

### ISSUE THREAD

**Issue by lovitus** [chen08209/FlClash#540]
作者你好，  非常抱歉打扰下。

很久就想用FLclash代替 比如 clash verge rev 等版本，  但是tun模式一直困扰着我。 
- 比如“Admin auto launch” 开启， 程序自动提权了， tun没有效果。
- 或者完整退出重新打开， tun也是不生效。
- 就算 Dashboard和Tools 里都显示tun是开启着， 实际网卡压根没生成。

其中的问题：
- 设置和实际效果不一致
- 以及显示和实际运作不一致。

这个请问是否后面会考虑优化？

我知道勾选“使用管理员打开” 这种windows兼容性选项可以让程序正常运行， 但是在电脑自动重启等情况，用户没法及时点击授权提权。
其他应用使用的服务模式，也就是单独注册一个服务用来处理tun，这样用户就不用管安装以后的权限问题了。

非常感谢作者写出这样优秀的应用， 我在android上已经主用了， 希望windows也能越来越好用。  如果添加或者优化功能会占用您太多时间， 希望考虑能在UI上能准确反映tun的运行状态。
谢谢

**Comment by lovitus** [comment]
另外在mac  apple silicon上使用，  不管怎么调整， tun都没有用。 
真的绝望

**Comment by refined-fish** [comment]
确实是需要一个服务模式，不然每次Windows都需要右键管理员运行很麻烦

**Comment by chen08209** [comment]
最新windows版已支持
