### ISSUE TITLE
安卓端能否被外部Shell脚本控制开与关？

### ISSUE THREAD

**Issue by gituser056391** [chen08209/FlClash#545]
如果能，具体Shell脚本是什么呢？

如果不能，建议支持这个特性

我需要通过MacroDroid之类的工具在一定条件下自动触发控制FlClash的开与关

**Comment by kljjh** [comment]
发送intent设置action=com.follow.clash.action.CHANGE可以切换 但是会调用flclash到前台

**Comment by Wwyxa** [comment]
https://github.com/chen08209/FlClash/issues/564#issuecomment-2478227292
这里给出了一个可用的命令

**Comment by yjf2614** [comment]
> 发送intent设置action=com.follow.clash.action.CHANGE可以切换 但是会调用flclash到前台

楼下的SHELL命令也会调用FLCLASH到前台,有没有解决办法?

> [#564 (comment)](https://github.com/chen08209/FlClash/issues/564#issuecomment-2478227292) 这里给出了一个可用的命令

**Comment by Wwyxa** [comment]
> > 发送intent设置action=com.follow.clash.action.CHANGE可以切换 但是会调用flclash到前台
> 
> 楼下的SHELL命令也会调用FLCLASH到前台,有没有解决办法?
> 
> > [#564 (comment)](https://github.com/chen08209/FlClash/issues/564#issuecomment-2478227292) 这里给出了一个可用的命令

如果事先已经打开了FlClash，运行命令会使它到前台，没有打开则不会
