### ISSUE TITLE
Windows任务栏状态图标显示异常

### ISSUE THREAD

**Issue by YanBai233** [chen08209/FlClash#548]
## Windows任务栏状态图标显示异常 ##
系统：Windows11 24H2
软件：FlClash 0.8.67
## 问题描述 ##
**无论开启还是关闭代理**，任务栏图标都保持常亮“蓝色”，但是有小概率触发图标“闪烁”（即蓝色突然变为黑色又变为蓝色）。

**Comment by zym20192019** [comment]
我也是有同样的问题，等待作者修复吧
