### ISSUE TITLE
F-Droid repo is not updated

### ISSUE THREAD

**Issue by cesaryuan** [chen08209/FlClash#557]
The version in https://chen08209.github.io/FlClash-fdroid-repo/repo/index-v1.json is still 0.8.63

**Comment by liolok** [comment]
Should also disable auto checking update by default for F-Droid repo version, it's already managed by F-Droid client after all.

**Comment by joyoner** [comment]
same issue

**Comment by joyoner** [comment]
"versionCode": 202412081,   好像是手误了，1008->1208
