### ISSUE TITLE
问题请教，系统代理和虚拟网卡有什么用

### ISSUE THREAD

**Issue by geofen** [chen08209/FlClash#560]
rt
问题请教，系统代理和虚拟网卡有什么用

**Comment by paras-zomby** [comment]
大概说说我的理解，系统代理是windows提供的代理接口，所有应用程序可以自愿遵守windows代理规则也可以不遵守（浏览器都是遵守的，其他应用不好说）；虚拟网卡原理是clash新建了一个虚拟网卡，检查所有经过虚拟网卡的流量判断是否需要代理，这样的方式保证所有的请求都会经过clash判断是否代理。

**Comment by geofen** [comment]
> 大概说说我的理解，系统代理是windows提供的代理接口，所有应用程序可以自愿遵守windows代理规则也可以不遵守（浏览器都是遵守的，其他应用不好说）；虚拟网卡原理是clash新建了一个虚拟网卡，检查所有经过虚拟网卡的流量判断是否需要代理，这样的方式保证所有的请求都会经过clash判断是否代理。

厉害

**Comment by TIANp44** [comment]
> 大概说说我的理解，系统代理是windows提供的代理接口，所有应用程序可以自愿遵守windows代理规则也可以不遵守（浏览器都是遵守的，其他应用不好说）；虚拟网卡原理是clash新建了一个虚拟网卡，检查所有经过虚拟网卡的流量判断是否需要代理，这样的方式保证所有的请求都会经过clash判断是否代理。

那是不是可以利用虚拟网卡做到手机连电脑wifi也可以做到科学上网呢

**Comment by paras-zomby** [comment]
> > 大概说说我的理解，系统代理是windows提供的代理接口，所有应用程序可以自愿遵守windows代理规则也可以不遵守（浏览器都是遵守的，其他应用不好说）；虚拟网卡原理是clash新建了一个虚拟网卡，检查所有经过虚拟网卡的流量判断是否需要代理，这样的方式保证所有的请求都会经过clash判断是否代理。
> 
> 那是不是可以利用虚拟网卡做到手机连电脑wifi也可以做到科学上网呢

是的，而且不用虚拟网卡也可以，在设置里打开允许局域网访问，在手机里设置代理服务器地址为电脑的局域网ip+clash代理端口也可以，相当于系统代理。但是没什么用，不如手机直接装一个clash。

**Comment by liangie** [comment]
我有两台macbook，一台上，不打开虚拟网卡选项就不能上网，但是另一台又没这个问题，很奇怪

**Comment by S-exypig** [comment]
请教一下，那我只需要打开虚拟网卡，而不用打开系统代理是吗？还是两个都要打开？
那只打开虚拟网卡的情况下，出站模式应该怎么设置呢？使用规则还是全局？感谢🙏

**Comment by incredible404-rgb** [comment]
> 请教一下，那我只需要打开虚拟网卡，而不用打开系统代理是吗？还是两个都要打开？ 那只打开虚拟网卡的情况下，出站模式应该怎么设置呢？使用规则还是全局？感谢🙏

挖坟，可能你现在已经搞明白了，不过我碰巧看到了还是说明一下：虚拟网卡和系统代理理论上开一个就行，但是在一些代理软件里（例如clash verge rev的一些版本）会把逻辑写成：系统代理的一个开关同时操控两个功能：开启代理服务+系统代理模式，这时候如果你想要使用虚拟网卡模式，系统代理和虚拟网卡两个开关需要同时打开（即只打开虚拟网卡开关只是切换到这个模式，而没有开启代理服务）；至于设置规则还是全局就看你的具体需求了，有些软件和网站ip检测比较严格，比如ai和网盘，规则连不上就需要开全局；
至于虚拟网卡和系统代理哪个更好，这是我正在探索的问题，我之前觉得虚拟网卡更底层更稳定一些，但是用得越多发现系统代理貌似具有切换速度快和Bug更少的优势......

**Comment by itwxb** [comment]
可以加上我的理解，我现在使用一个编程软件，里边一个模型需要美国IP才能用，我是这么设置的。就能正常使用了。如果不开虚拟网卡的话，CMD终端还是没走VPN，只有开了虚拟网卡才需要走VPN，我使用的也是规则模式

<img width="734" height="592" alt="Image" src="https://github.com/user-attachments/assets/7cbce748-9f89-49cb-be44-1cee4d0d71fa" />

<img width="769" height="358" alt="Image" src="https://github.com/user-attachments/assets/5bd70bdf-31ec-449f-9f3e-973fd5f15f8f" />
