### ISSUE TITLE
WIN11 显示白屏，无法进入应用程序

### ISSUE THREAD

**Issue by iwitsky** [chen08209/FlClash#563]
![QQ截图20241115091036](https://github.com/user-attachments/assets/f4907d99-9974-43f9-aa74-0139790c357d)

系统：

版本	Windows 11 专业版
版本号	24H2
安装日期	‎2024/‎10/‎11
操作系统版本	26100.2314
体验	Windows Feature Experience Pack 1000.26100.32.0

**Comment by daiz89** [comment]
相同的问题。电脑睡眠再唤醒后，打开程序就是白屏。
