### ISSUE TITLE
Android平台上停止连接后VpnService没有停止

### ISSUE THREAD

**Issue by Littleweisheit** [chen08209/FlClash#564]
这样会影响
`am start-foreground-service com.follow.clash/.services.FlClashVpnService`
开启连接
隔壁ClashX Meta没这个问题。因为关闭后这个服务就关闭，希望也能自动关闭。
有其他方法开启连接也可以。主要是要用自动化开启连接。
![Screenshot_20241115-130114](https://github.com/user-attachments/assets/bd53e161-515b-441f-84f8-ef4027290cee)

**Comment by Littleweisheit** [comment]
或者在activity里面添加一个切换。
![Screenshot_20241115-150659](https://github.com/user-attachments/assets/705b45e3-105d-4e1e-80e5-ca0e12450889)

**Comment by Littleweisheit** [comment]
或者在activity里面添加一个切换。
![Uploading Screenshot_20241115-150659_1.png…]()

**Comment by Littleweisheit** [comment]
或者在activity里面添加一个切换。
![Screenshot_20241115-150659_1](https://github.com/user-attachments/assets/73ef9baa-feba-4533-93b5-11201ce8a87c)

**Comment by Littleweisheit** [comment]
shell am start -n com.follow.clash/.TempActivity -a com.follow.clash.action.CHANGE -c android.intent.category.DEFAULT
可以用上面的shell命令切换

**Comment by yjf2614** [comment]
> shell am start -n com.follow.clash/.TempActivity -a com.follow.clash.action.CHANGE -c android.intent.category.DEFAULT 可以用上面的shell命令切换

这只是切换. 是否把‘CHANG‘改为’Start‘就是启动命令?
如果不是,启动命令是什么?(关闭我可以㷱强制关闭程序解决)

**Comment by Littleweisheit** [comment]
> > shell am start -n com.follow.clash/.TempActivity -a com.follow.clash.action.CHANGE -c android.intent.category.DEFAULT 可以用上面的shell命令切换
> 
> 这只是切换. 是否把‘CHANG‘改为’Start‘就是启动命令? 如果不是,启动命令是什么?(关闭我可以㷱强制关闭程序解决)

启动是这个
`am start -n com.follow.clash/.TempActivity -a com.follow.clash.action.CHANGE -c android.intent.category.DEFAULT`

关闭是
`am start -n com.follow.clash/.TempActivity -a com.follow.clash.action.STOP -c android.intent.category.DEFAULT`

**Comment by yjf2614** [comment]
> > > shell am start -n com.follow.clash/.TempActivity -a com.follow.clash.action.CHANGE -c android.intent.category.DEFAULT 可以用上面的shell命令切换
> > 
> > 
> > 这只是切换. 是否把‘CHANG‘改为’Start‘就是启动命令? 如果不是,启动命令是什么?(关闭我可以㷱强制关闭程序解决)
> 
> 启动是这个 `am start -n com.follow.clash/.TempActivity -a com.follow.clash.action.CHANGE -c android.intent.category.DEFAULT`
> 
> 关闭是 `am start -n com.follow.clash/.TempActivity -a com.follow.clash.action.STOP -c android.intent.category.DEFAULT`

验证了一遍,Change确实只是切换,来回切换. 启动是用START
正确的启动命令应该是:
am start -n com.follow.clash/.TempActivity -a com.follow.clash.action.START -c android.intent.category.DEFAULT

谢谢!

**Comment by yjf2614** [comment]
原来pixel 5(root) ,换pixel 7pro(未Root), 发送又回到起点了,两要条指令都不能使用.
tasker用发送intent的方式控制. 
clashmeta正常的,flclash不行,不知道怎么回事
只能又回到clashmeta

**Comment by a0iwguf09u** [comment]
> am start -n com.follow.clash/.TempActivity -a com.follow.clash.action.START -c android.intent.category.DEFAULT

这个好用！谢谢🙏
