### ISSUE TITLE
你好,请出一个完整客户端配置 文档,谢谢.

### ISSUE THREAD

**Issue by gsuns** [chen08209/FlClash#569]
我试过一些配置,例如 Tun  出站H2 GEOIP等,都无法正常工作.
我找不到原因,不知道是不是我自己配置错误.
所以.....希望能给个完整的配置文档参考下.
感谢

**Comment by Zxis233** [comment]
请自行查阅mihomo文档。

**Comment by gsuns** [comment]
OK, 感谢
