### ISSUE TITLE
请把订阅请求加上UA头，用于客户端版本识别和特定配置下发

### ISSUE THREAD

**Issue by moranno** [chen08209/FlClash#57]
请把订阅请求加上UA头，用于客户端版本识别和特定配置下发。

格式可以采用类似这样：
Flclash/0.8.24 platform/android ClashMeta/1.18.5 (Perfer ClashMeta Format)

**Comment by chen08209** [comment]
已修改: 
FlClash/v0.8.33  clash-verge/v1.6.6  Platform/android
