### ISSUE TITLE
任务栏的图标不能通过蓝色\灰色区分了，希望能更新一下

### ISSUE THREAD

**Issue by qincunxiang** [chen08209/FlClash#579]
不论链接没链接，任务栏的图标都是蓝色，不在通过蓝色\灰色区分了，希望能更新一下

**Comment by synn** [comment]
正想提一个issue呢，帮你顶一下。

**Comment by kangluyao** [comment]
也想提一下这个问题。设置了快捷键开启和关闭，每次按快捷键开启和关闭，看不出来到底是开着还是关着，还得点开面板看一下
