### ISSUE TITLE
功能请求: 安卓版本增加后台保活

### ISSUE THREAD

**Issue by nonlog** [chen08209/FlClash#59]
电池策略设为"无限制", 忽略电池优化, 划掉后台卡片服务仍会被关闭, 用返回键返回桌面, 服务也会被关闭.
折中的办法是使用控制中心快捷方式启动 VPN, 但是每次打开应用划掉后台后又要手动开启 VPN, 有些不方便. 希望可以增加保活机制.

**Comment by XiandaLyu** [comment]
啥系统啊？后台加不了锁吗？而且都后台无限制电池不优化了这明显不是软件的问题了

**Comment by windy1lee** [comment]
应该是你系统的问题，和app无关

**Comment by XiandaLyu** [comment]
> @XiandaLyu @windy1lee 并不是, 在反馈群组里看到开发者说过这是预期行为, 设计如此, 开一个 issue 只是希望开发者考虑以后修改后台逻辑.
> 况且, 你们说这是我系统问题, 你们使用时划卡服务不会被关闭?

我的锁后台了 不会啊
