### ISSUE TITLE
【建议】能否在订阅内容缺失proxy-groups字段的情况下默认添加proxy-groups字段

### ISSUE THREAD

**Issue by lakevilladom** [chen08209/FlClash#598]
如题，能否在订阅内容缺失proxy-groups字段的情况下默认添加proxy-groups字段，比如如下：
```
proxy-groups:
    - { name: Flash, type: select, include-all: true, proxies: [自动选择, 故障转移] }
    - { name: 自动选择, type: url-test, include-all: true, url: 'http://www.gstatic.com/generate_204', interval: 86400 }
    - { name: 故障转移, type: fallback, include-all: true, url: 'http://www.gstatic.com/generate_204', interval: 7200 }
```
遇到有的订阅只有proxies字段，其他内容都是软件配置或者覆写产生

**Comment by refined-fish** [comment]
> 如题，能否在订阅内容缺失proxy-groups字段的情况下默认添加proxy-groups字段，比如如下：
> 
> ```
> proxy-groups:
>     - { name: Flash, type: select, include-all: true, proxies: [自动选择, 故障转移] }
>     - { name: 自动选择, type: url-test, include-all: true, url: 'http://www.gstatic.com/generate_204', interval: 86400 }
>     - { name: 故障转移, type: fallback, include-all: true, url: 'http://www.gstatic.com/generate_204', interval: 7200 }
> ```
> 
> 遇到有的订阅只有proxies字段，其他内容都是软件配置或者覆写产生

这种情况你应该自自行修改配置文件，或者套一下订阅转换，软件实现的意义不是很大
