### ISSUE TITLE
Mihomo kernel

### ISSUE THREAD

**Issue by fildunsky** [chen08209/FlClash#603]
Thank you so much for amazing app, I love design a lot and most of the things are perfect for me. One thing is that Clash Dashboard showing 1.10 kernel version. I've tried to update it via Dashboard with no luck. Any way to use latest stable Mihomo kernel? I can download it manually but don't understand where should I put it in FlClash for Android, Windows and Linux.

**Comment by fildunsky** [comment]
> You need to update the git submodule core/Clash.Meta to the new upstream version and then compile the application.
Unfortunately I am not that tech saavy, but thank you so much for your answer, at least now I know it's possible. Mihomo has an Amnezia support since 1.18.9 if I am not mistaken and I need it a lot to obfuscate WG. I'll try to do what you suggested, thanks!

**Comment by chen08209** [comment]
The mihomo kernel cannot obtain the latest version number at the code level. Currently, the kernel version of FlClash is almost equal to the latest mihomo kernel.

**Comment by fildunsky** [comment]
Thank you so much for clearing this out to me! Really appreciate that!
