### ISSUE TITLE
不能自动优选节点吗？

### ISSUE THREAD

**Issue by Mubai-meng** [chen08209/FlClash#606]
版本：0.8.68
软件代理开关打开后经常发生上不去网，需要去软件里手动选择节点才行。
不能自动优选节点嘛？希望开启代理后如果节点坏了可以自动换好的节点

**Comment by refined-fish** [comment]
> 版本：0.8.68 软件代理开关打开后经常发生上不去网，需要去软件里手动选择节点才行。 不能自动优选节点嘛？希望开启代理后如果节点坏了可以自动换好的节点

这个不是软件问题，是你配置文件的问题吧，优选节点比如自动选择代理组，需要你自己配置订阅文件
![image](https://github.com/user-attachments/assets/eb017a1b-f62b-434d-9f4f-88983d9cd8d1)

**Comment by Mubai-meng** [comment]
> > 版本：0.8.68 软件代理开关打开后经常发生上不去网，需要去软件里手动选择节点才行。 不能自动优选节点嘛？希望开启代理后如果节点坏了可以自动换好的节点
> 
> 这个不是软件问题，是你配置文件的问题吧，优选节点比如自动选择代理组，需要你自己配置订阅文件
> ![image](https://github.com/user-attachments/assets/eb017a1b-f62b-434d-9f4f-88983d9cd8d1)
> 

应该是，但是我的订阅没有配置文件，我是节点通过订阅转换网站转成订阅的，如果软件自带优选功能就好了

**Comment by refined-fish** [comment]
> > > 版本：0.8.68 软件代理开关打开后经常发生上不去网，需要去软件里手动选择节点才行。 不能自动优选节点嘛？希望开启代理后如果节点坏了可以自动换好的节点
> > 
> > 
> > 这个不是软件问题，是你配置文件的问题吧，优选节点比如自动选择代理组，需要你自己配置订阅文件
> > ![image](https://private-user-images.githubusercontent.com/93998080/391211245-eb017a1b-f62b-434d-9f4f-88983d9cd8d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NDE0MTMsIm5iZiI6MTczMjk0MTExMywicGF0aCI6Ii85Mzk5ODA4MC8zOTEyMTEyNDUtZWIwMTdhMWItZjYyYi00MzRkLTlmNGYtODg5ODNkOWNkOGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTMwVDA0MzE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMjRiMTQ1ZGNkNzMwOTNjMDZmMGQzYmFlYTdkODM5ODQ3Yjc4NmRjNzA0MDlkZTczMTBlNDE1MTQ5MGE1OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tPHI6RTe0tVd2P9g6PsoXzMm85cMcbGJZQXGBWkSnMY)
> 
> 应该是，但是我的订阅没有配置文件，我是节点通过订阅转换网站转成订阅的，如果软件自带优选功能就好了

那么你可以选择一个有自动选择代理组的订阅转换模板。另外你没理解意思，不是软件的问题就是说，这个就不是软件实现的问题，这个要实现需要对你提供的配置文件进行覆写，可以做但很没必要，也比较麻烦

**Comment by Mubai-meng** [comment]
> > > > 版本：0.8.68 软件代理开关打开后经常发生上不去网，需要去软件里手动选择节点才行。 不能自动优选节点嘛？希望开启代理后如果节点坏了可以自动换好的节点
> > > 
> > > 
> > > 这个不是软件问题，是你配置文件的问题吧，优选节点比如自动选择代理组，需要你自己配置订阅文件
> > > ![image](https://private-user-images.githubusercontent.com/93998080/391211245-eb017a1b-f62b-434d-9f4f-88983d9cd8d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NDE0MTMsIm5iZiI6MTczMjk0MTExMywicGF0aCI6Ii85Mzk5ODA4MC8zOTEyMTEyNDUtZWIwMTdhMWItZjYyYi00MzRkLTlmNGYtODg5ODNkOWNkOGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTMwVDA0MzE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMjRiMTQ1ZGNkNzMwOTNjMDZmMGQzYmFlYTdkODM5ODQ3Yjc4NmRjNzA0MDlkZTczMTBlNDE1MTQ5MGE1OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tPHI6RTe0tVd2P9g6PsoXzMm85cMcbGJZQXGBWkSnMY)
> > 
> > 应该是，但是我的订阅没有配置文件，我是节点通过订阅转换网站转成订阅的，如果软件自带优选功能就好了
> 
> 那么你可以选择一个有自动选择代理组的订阅转换模板。另外你没理解意思，不是软件的问题就是说，这个就不是软件实现的问题，这个要实现需要对你提供的配置文件进行覆写，可以做但很没必要，也比较麻烦

好的，感谢大佬解答
