### ISSUE TITLE
TimeoutException after 0:00:30.000000: Future not completed

### ISSUE THREAD

**Issue by linZsama** [chen08209/FlClash#607]
MAC OS  M1
版本: 0.8.68

**Comment by cyydark** [comment]
相同的问题
MAC OS M2
系统版本：15.1.1 (24B91)
版本：0.8.68

**Comment by linZsama** [comment]
> 相同的问题
> MAC OS M2
> 系统版本：15.1.1 (24B91)
> 版本：0.8.68

你转一下链接就好了
