### ISSUE TITLE
功能请求：一键开关

### ISSUE THREAD

**Issue by Cylidvirus** [chen08209/FlClash#61]
求大佬在安卓平台添加一键开关小部件和下拉栏一键开关快捷方式

**Comment by J926L** [comment]
![Screenshot_2024-06-20-23-22-37-932_com miui home](https://github.com/chen08209/FlClash/assets/63765903/6f467901-7510-4975-9d7f-4b498daf3b79)
已经有了啊

**Comment by Cylidvirus** [comment]
嗷嗷，不好意思我瞎了，上次找了几遍都没看见
