### ISSUE TITLE
[BUG]在计数器到达99:59:59后不跳变

### ISSUE THREAD

**Issue by 100pangci** [chen08209/FlClash#610]
![IMG_20241130_194023_977.jpg](https://github.com/user-attachments/assets/d15cbcf2-9555-4278-bc8c-dca235650629)

如图所示

**Comment by liyunlong5** [comment]
作者提醒你不要开太长时间，哈哈

**Comment by 100pangci** [comment]
> 不是致命问题，另外你也开太长时间了吧hh🤣

这不显得您软件稳定吗😭
