### ISSUE TITLE
请问这个是不是也不能在Google TV Streamer/Android 14上安装使用？

### ISSUE THREAD

**Issue by supermansaga** [chen08209/FlClash#617]
我是听说能兼容安卓14过来的，但试了一下v0.8.68好像无法安装。跟115的16.5.0 for TV一样。谢谢。理论上应该是用FlClash-0.8.68-android-arm64-v8a.apk吧？

**Comment by fdpsss** [comment]
用v7的，v8是64位手机之类的高端cpu用

**Comment by supermansaga** [comment]
Clash Meta for Android突然又可以安装了。。。v8的确不行，v7可以，但我见到clash meta可以，我就暂时不装fclash了。
