### ISSUE TITLE
启动与否代理更改图标样式

### ISSUE THREAD

**Issue by Cylidvirus** [chen08209/FlClash#618]
是否可以添加一个代理启用时缩略图标特殊标志方便查看当前是否进行代理，类似clash和v2ray那种，也方便全局快捷键观察是否生效

**Comment by arthurfsy2** [comment]
之前版本在关闭代理时 桌面右下角小图标是灰色的，最新版0.8.68就不行了

**Comment by refined-fish** [comment]
早期已声明，由于软件跨平台维护，但是Windows没有提供现成的api，软件要实现全平台的颜色切换太过复杂，目前仅支持有api的MacOS平台切换图标样式，[具体请参考原始问题](https://github.com/chen08209/FlClash/issues/513#issue-2623624868)
