### ISSUE TITLE
关于全局模式不生效的BUG

### ISSUE THREAD

**Issue by selfwong** [chen08209/FlClash#620]
设备：小米14U
系统：澎湃OS2 (Android 15)
版本：0.8.68
问题：使用全局模式后打开某些APP显示的IP仍然为运营商网络的本地IP而并非代理和节点IP，但使用Surfboard（代理软件）则是真全局....，不管国内外都走代理网络，希望能修一下

**Comment by selfwong** [comment]
经过我自己慎重核实，问题已解决，没有该BUG，被自己蠢到了

**Comment by ZZ0YY** [comment]
> 设备：小米14U
> 系统：澎湃OS2 (Android 15)
> 版本：0.8.68
> 问题：使用全局模式后打开某些APP显示的IP仍然为运营商网络的本地IP而并非代理和节点IP，但使用Surfboard（代理软件）则是真全局....，不管国内外都走代理网络，希望能修一下

能否问一下你是如何核实的 我这边全局也不起作用（🤦‍♂️）
