### ISSUE TITLE
安卓好像有内存泄露

### ISSUE THREAD

**Issue by LM-Firefly** [chen08209/FlClash#64]
![Screenshot_2024-06-20-11-23-00-131_com.follow.clash.jpg](https://github.com/chen08209/FlClash/assets/20715220/9f13f8c4-65aa-4b67-948b-a9b80537fef1)

![Screenshot_2024-06-20-11-23-05-377_com.follow.clash.jpg](https://github.com/chen08209/FlClash/assets/20715220/24dd3338-deb2-4a3a-9cf0-a38d39ccd590)

![Screenshot_2024-06-20-11-22-53-901_com.android.settings.jpg](https://github.com/chen08209/FlClash/assets/20715220/182e45c3-a4ae-444e-abb1-b27f1c7dc81f)

内存占用1G多了

**Comment by J926L** [comment]
小米吗？

**Comment by LM-Firefly** [comment]
> 小米吗？

是的，

**Comment by chen08209** [comment]
目前已知反复切换配置会造成内存增大，通常使用内存应该是正常的，你可以打开外部控制进入xd面板看看内核占用的内存
