### ISSUE TITLE
延迟测试地址有问题

### ISSUE THREAD

**Issue by yutian81** [chen08209/FlClash#68]
软件内置的延迟测试地址有问题，很多节点是通的，但是延迟测试显示超时。
建议修改默认的地址为http://www.gstatic.com/generate_204
同时内置以下延迟测试地址以供用户选择：
Apple：http://www.apple.com/library/test/success.html 对中国大陆和境外都是最友好的
高通：http://www.qualcomm.cn/generate_204 对中国大陆和境外都是最友好的
Google：https://www.gstatic.com/generate_204 TLS延迟会比较高，但会杜绝一些假延迟的情况
Microsoft：http://www.msftconnecttest.com/connecttest.txt 入口一般

**Comment by chen08209** [comment]
之后会提供统一修改延迟测试地址

**Comment by Kia678** [comment]
可以默认为：
Apple：http://www.apple.com/library/test/success.html 对中国大陆和境外都是最友好的

另外，如题：辛苦大佬支持下mihomo内核的unified-delay与tcp-concurrent、global-client-fingerprint特性
![image](https://github.com/chen08209/FlClash/assets/85081567/df95cfe0-6b91-42e9-b5f8-6a985f8e18d2)
