### ISSUE TITLE
user agent是clash meta的开头嚒

### ISSUE THREAD

**Issue by zdyzsb** [chen08209/FlClash#70]
user agent是啥咧

**Comment by habbiedevS** [comment]
目前的ua应该是clash.meta

**Comment by zdyzsb** [comment]
> 目前的ua应该是clash.meta

能不能改成flclash之类的呢 我好过白

**Comment by chen08209** [comment]
现在ua已经改成: 
FlClash/v0.8.33  clash-verge/v1.6.6  Platform/android
