### ISSUE TITLE
通过URL订阅时出现超时错误，开启代理和不开启都订阅不了

### ISSUE THREAD

**Issue by xiaobailong6** [chen08209/FlClash#72]
通过URL订阅时出现超时错误，开启代理和不开启都订阅不了，同一设备+同一网络在CFA可正常更新
![20240620215511](https://github.com/chen08209/FlClash/assets/23652026/9652951b-03da-4922-9975-ca091f0093c4)

**Comment by Voya9e** [comment]
有更换网络吗？或者在其它客户端测试过链接吗？
