### ISSUE TITLE
异常的内存占用

### ISSUE THREAD

**Issue by YanBai233** [chen08209/FlClash#74]
# 关于Windows端出现的异常内存占用问题 #
软件版本：0.8.27
系统版本：Windows 11 23H2
## 问题表现 ##
- 在使用软件一段时间后（开启代理运行），内存占用呈现阶段性上涨（每10分钟上涨40MB左右）且未停留在一个正常范围，软件出现了异常的内存占用。
- 随着内存占用的升高，软件代理性能出现明显下降。具体表现为延迟的大幅上升（150ms到接近2000ms）；系统出现卡顿。
- 重启软件后，恢复正常，但内存无限上涨问题依旧存在。
- 如下图

![QQ截图20240624214014](https://github.com/chen08209/FlClash/assets/54111576/af3fb14e-2bfd-4179-92ab-a08fcf40e0b6)
## 问题排除 ##
- 无论是否开启Geo低内存模式，问题依旧。
- 关闭了日志捕获。
- 此前各版本均出现此问题，虽然较此前稍有缓解，但是问题依旧。

**Comment by YanBai233** [comment]
### 内存增长图 ###
![QQ截图20240625000107](https://github.com/chen08209/FlClash/assets/54111576/c275cc79-a53a-402e-9a35-0633213e50fe)

**Comment by chen08209** [comment]
是否能提供脱敏后的配置文件，我这边长时间使用基本能排除应用端的内存泄露，但是无法判断内核是否存在内存泄露

**Comment by YanBai233** [comment]
[配置文件.yaml.txt](https://github.com/user-attachments/files/15981916/yaml.txt)

**Comment by chen08209** [comment]
因为不是脱敏发过来的，所以帮你删除了，然后我现在开始尝试处理这块的问题

**Comment by chen08209** [comment]
目测用过是修复了
