### ISSUE TITLE
覆写功能咨询

### ISSUE THREAD

**Issue by Guciliang** [chen08209/FlClash#75]
询问一下作者，FlClash的覆写功能如果不打开是否会自动修改配置文件中的内容以及是否不同os间有不同的设定。
open clash会进行修改，例如已经在配置中开启的功能，如果open clash覆写那里没开，open clash 就会将配置文件中已经开了的功能关了。
还有就是开启FlClash覆写功能中webui开关，如果配置文件中没有设置是否会修改配置文件并添加webui文件，我自己的配置文件是只设置了webui的开关以及端口没有指定webui文件，在使用127.0.0.1:9090/ui/metacubexd测试后没有打开webiui，是否是我的使用有问题？

**Comment by chen08209** [comment]
覆写会默认覆盖配置中的选项，外部控制器目前仅支持预设地址，即开启后开放127.0.0.1:9090。

**Comment by Guciliang** [comment]
> 覆写会默认覆盖配置中的选项，外部控制器目前仅支持预设地址，即开启后开放127.0.0.1:9090。

了解了，这就去把我在配置中开启的功能在覆写里也打开，非常感谢作者的回复。我这边没有问题了，可以关了。
