### ISSUE TITLE
bug:订阅响应头，覆写字段

### ISSUE THREAD

**Issue by habbiedevS** [chen08209/FlClash#76]
1、订阅链接之前没有订阅响应头，之后有的话，更新订阅不会覆盖之前的设置
2、profile中的ipv6/allowlan/unified delay/tcp concurrent等字段无法被软件读取，软件中的override功能会将原有配置覆盖

**Comment by chen08209** [comment]
后者设计如此，前者每次更新成功后远程获取的响应头信息除名称外会覆盖原有信息。
