### ISSUE TITLE
遇到的很影响正常使用的bug

### ISSUE THREAD

**Issue by alittlestars** [chen08209/FlClash#86]
问题一：
软件界面使用侧滑返回桌面会自动反复又进入软件，且侧滑过程中卡顿明显不跟手；

https://github.com/chen08209/FlClash/assets/81513580/c544e5a8-3044-4c7f-984a-33431a2b448c

问题二：
订阅配置界面设置的自动更新不生效，且订阅的更新时间不会变化，一直就显示最初导入订阅时候的更新时间或者最后一次更新的时间；
![Screenshot_2024-06-28-18-19-47-740_com follow clash](https://github.com/chen08209/FlClash/assets/81513580/26bc2c3b-101a-4f2b-8ee7-b151247cda0a)

问题三：
编辑订阅配置界面在启动运行代理的时候，输入法会自动收起，无法输入，关闭代理后，输入恢复正常。

https://github.com/chen08209/FlClash/assets/81513580/39ea450a-5402-4203-b39b-f60211e44e46

**Comment by chen08209** [comment]
什么型号的手机

**Comment by alittlestars** [comment]
> 什么型号的手机

小米14
![Screenshot_2024-06-28-20-30-15-312_com android settings](https://github.com/chen08209/FlClash/assets/81513580/4b9a0a6b-3379-4113-8336-1dba5ae0edf4)

**Comment by chen08209** [comment]
最新版本应该解决了
