### ISSUE TITLE
缺少绕过网络/域的功能

### ISSUE THREAD

**Issue by autocpp** [chen08209/FlClash#87]

**Comment by user20161119** [comment]
也在找这个功能，找了半天没找到，开发人员经常需要跳过指定域名，类似，Clash的配置
![image](https://github.com/user-attachments/assets/70ec96a0-eb89-4182-80fd-f10477d4026f)
![image](https://github.com/user-attachments/assets/08db9563-6a3f-44b8-9f21-dd7e90848359)

**Comment by fans1106** [comment]
i need such function too

**Comment by keethebest** [comment]
开发环境，很多域名是需要不通过代理访问的，需要额外设置很多规则，很不方便。希望能提供这个功能。
