### ISSUE TITLE
在没有启动系纹代理的情况下，为什么在启动后，系统里的代理还是会被修改成127.0.0.1:7890呢？

### ISSUE THREAD

**Issue by hzdlive** [chen08209/FlClash#98]
在没有启动系纹代理的情况下，为什么在启动后，系统里的代理还是会被修改成127.0.0.1:7890呢？

![微信图片_20240706093643](https://github.com/chen08209/FlClash/assets/3319136/02af9175-c00c-484e-a517-79d33a2bd22d)

只想通过浏览器插件SwitchyOmega走FlClash，而不影响整个系统的网络。

**Comment by wenliyang** [comment]
FlClash  的设计似乎是启动后就自动打开系统代理，不太明白为何这样做，同楼上，希望能给出设置让用户选择是否启用

**Comment by shabby2333** [comment]
不用点界面上的启动按钮，那个按钮的作用是打开系统代理

**Comment by hzdlive** [comment]
> 不用点界面上的启动按钮，那个按钮的作用是打开系统代理

那不点的话，界面那些流量信息都没有变化了呀

**Comment by shabby2333** [comment]
> > 不用点界面上的启动按钮，那个按钮的作用是打开系统代理
> 
> 那不点的话，界面那些流量信息都没有变化了呀

确实没有变化，但是我也确实没管（因为懒得看）
我现在就是 不点启动按钮  直接插件手动设置 用起来没啥问题

**Comment by hzdlive** [comment]
我电脑一般也就是浏览器走梯子，其他的应用不走梯子，所以在没有弄清楚那个按钮的功能之前，总以为是我的梯子的问题

**Comment by okhowang** [comment]
那是不是可以对桌面端增加一个功能 就是哪怕没有打开系统代理 也实时刷新流量统计/网络速度等功能

**Comment by chen08209** [comment]
设计如此，目前的流量统计仅统计开启状态下的流量

**Comment by yixiuge301** [comment]
这个是你关机的时候代理没正常退出吧？印象中用 cfw 的时候，也有这种情况。

**Comment by Eyion** [comment]
要实现自动分流，是不是要关闭系统代理并设置访问控制？没有tun模式吗？
